### ISSUE TITLE
Remove large dependencies

### ISSUE THREAD

**Issue by Cretezy** [streamich/react-use#102]
This library minified is almost 52kb, which is huge for what it is. 60% of the bundle size is solely based on dependencies, all of which are only used in a few hook.

I would suggest making turning those into `peerDependencies` and requiring users to include the libraries in their own `package.json`. This would make the size of this library ~21kB.

Although tree shaking *should* take care of this, not all environments support it, and forcing dependencies on users isn't the best course of action, especially if it's for a small functionality.

If this is a go, I could make the PR with the changes (code & docs) required for this.

**Comment by streamich** [comment]
That would be great, I think!

**Comment by ctrlplusb** [comment]
Always a great reference site:

https://bundlephobia.com/result?p=react-use@5.13.0

Could also be a good idea to update the build configuration for this package so that it additionally outputs an ES6 version (pointed at by the `module` key within `package.json`). 

I do this in my library, for example here is the package output:
https://unpkg.com/easy-peasy@2.1.1/

Some build systems (e.g. create-react-app) will then automatically use the ES6 version and treeshake accordingly.

**Comment by Cretezy** [comment]
@ctrlplusb bundlephobia is what prompted me to open this ticket, and is preventing us to use this because we don't want to bloat our bundle! 

Is there any progress on this!

**Comment by streamich** [comment]
> Is there any progress on this?

@Cretezy Well, [on Feb 7](https://github.com/streamich/react-use/issues/102#issue-407883999) you volunteered to make a PR :smile::

> If this is a go, I could make the PR with the changes (code & docs) required for this.

**Comment by Cretezy** [comment]
Ah damn I had never seen that comment! I'll start working on something when I have free time

**Comment by Cretezy** [comment]
Opened PR: https://github.com/streamich/react-use/pull/161

**Comment by wardoost** [comment]
I have been using [`babel-plugin-import`](https://github.com/ant-design/babel-plugin-import) for util packages like this one. Might be good to add something in the docs about this? `.babelrc` is pretty straight forward:

```json
{
  "plugins": [
    [
      "import", {
        "libraryName": "react-use",
        "libraryDirectory": "lib",
        "camel2DashComponentName": false
      }
    ]
  ]
}
```

**Comment by streamich** [comment]
Big dependencies are now in `peerDependencies` there are few dependencies this library installs but all of those are very minor:

- `copy-to-clipboard` &mdash; this is [just one file](https://github.com/sudodoki/copy-to-clipboard/blob/master/index.js) and used only if you use copy-to-clipboard hook.
- `nano-css` &mdash; this should add less than 1Kb to your bundle and only if you use `useCss` hook.
- `react-fast-compare` &mdash; this is just one function for deep comparison of objects.
- `react-wait` &mdash; this is `useWait` hook, will be included in your bundle only if you use `useWait` hook.
- `screenfull` &mdash; used for cross-browser compatibility only in `useFullscreen` hook.
- `throttle-debounce` &mdash; just two functions: throttle and debounce.
- `ts-easing` &mdash; list of easing functions for animations.

**Comment by huchenme** [comment]
@streamich I believe `create-react-app` have tree shaking enabled, but still not able to use es module syntax, getting `keyboardjs` missing error without installing those peerDependencies
