### ISSUE TITLE
A state hook to do and undo

### ISSUE THREAD

**Issue by arnaudNYC** [streamich/react-use#1022]
I wrote a simple state hook that allows to undo/redo changes to a state: https://github.com/arnaudNYC/useDo

`const [state, setState, undo, redo, canUndo, canRedo] = useDo(initialState);`

Calling `undo` reverts to the previous state, and calling `redo` undoes the last undo. The `canUndo` and `canRedo` are booleans indicating if the operation can be performed.

Is this something you'd be interested in having in this project? I'm happy to donate the code and open a PR here. Let me know.

**Comment by xobotyi** [comment]
He already have such hook: [useStateWithHistory](https://github.com/streamich/react-use/blob/master/docs/useStateWithHistory.md)

**Comment by arnaudNYC** [comment]
Thanks, good to know!
