### ISSUE TITLE
keyboardjs is loaded async, while useKeyPress is already trying to access it

### ISSUE THREAD

**Issue by jacargentina** [streamich/react-use#103]
I 've stuck with this, attached stack trace.

<img width="890" alt="captura de pantalla 2019-02-08 a la s 14 46 55" src="https://user-images.githubusercontent.com/517228/52495840-96750280-2bb0-11e9-89ac-5b25ab382596.png">

Originating here:

<img width="702" alt="captura de pantalla 2019-02-08 a la s 14 50 16" src="https://user-images.githubusercontent.com/517228/52495964-dfc55200-2bb0-11e9-833f-56e132f3b8ea.png">

KeyboardJS loading is like this:

<img width="609" alt="captura de pantalla 2019-02-08 a la s 14 51 40" src="https://user-images.githubusercontent.com/517228/52496033-10a58700-2bb1-11e9-8a93-d82b98687b31.png">

**Comment by jacargentina** [comment]
@streamich can you look? this is not letting me use this fantastic library, i dont want to install more deps please! 🙏

**Comment by streamich** [comment]
@jacargentina This might solve it: https://github.com/streamich/react-use/pull/110
