### ISSUE TITLE
[Question] Will usePromise leak memory?

### ISSUE THREAD

**Issue by rodw1995** [streamich/react-use#1056]
If I understand correctly with the use of the *usePromise* hook, we can create a promise that is never resolved. That will be the case if the component unmounts before the wrapped promise is resolved. I'm wondering if this can be a potential memory leak? Considering the following example:

```js
import {usePromise} from 'react-use';

export default () => {
  const mounted = usePromise();
  const [user, setUser] = useState();

  useEffect(() => {
    mounted(fetchAuthenticatedUser()).then((user) => {
      setUser(user);
    });
  });
};
```

Will the *then* handler be waiting indefinitely to call *setUser*? Or will it be garbage collected in someway? I hope someone can explain to me what will happen 🙂

I found [this](http://github.com/facebook/react/issues/5465) discussion which is maybe is related.

**Comment by kkirbatski-adig** [comment]
No. JavaScript is smart enough to garbage collect the promise.  I too had this question awhile back and found the answer in an article: https://web.archive.org/web/20200824215516/https://www.dankuck.com/2017/02/24/broken-js-promises.html

**Comment by kkirby** [comment]
No. JavaScript is smart enough to garbage collect the promise.  I too had this question awhile back and found the answer in an [article](https://web.archive.org/web/20200824215516/https://www.dankuck.com/2017/02/24/broken-js-promises.html)

**Comment by rodw1995** [comment]
Thanks, that article explains it well  🙂
