### ISSUE TITLE
Hook proposal: useDelayed

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [streamich/react-use#1063]
**Is your feature request related to a problem? Please describe.**
There are situations where one would want a `usePrevious` that waits some number of milliseconds before updating the value. For example, you might want to wait to delete an element until some number of milliseconds after an animation has started.

**Describe the solution you'd like**
A simple version of this hook might have an API like:

```js
const delayedValue = useDelayed(basis, delay);
```

...though it would probably be good to have it be able to take an optional third object value to allow folks who dependency inject `clearTimeout` & `setTimeout` to pass in their own [clock](https://www.npmjs.com/package/@sinonjs/fake-timers).

```js
const delayedValue = useDelayed(basis, delay, clock);
```

**Describe alternatives you've considered**
You could always write this yourself, but... I've done this a few times now, so it feels reasonable to standardize?

Roughly:

```js
const delay = 1000;
const [basis, setBasis] = useState("value");
const [delayed, setDelayed] = useState();

useEffect(() => {
    const handle = setTimeout(() => setDelayed(basis), delay);
    return () => clearTimeout(handle);
}, [basis, delay]);
```

**Comment by streamich** [comment]
I guess it could reuse the `useTimeout` hook:

```ts
const useDelayed = (value, delay) => {
  const [isReady] = useTimeout(value, delay);
  return isReady ? value : undefined;
};
```

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues I no longer have context on. If anybody else is still seeing this, I'd encourage you to file a new issue with more information. Cheers!
