### ISSUE TITLE
useSetState doesn't work

### ISSUE THREAD

**Issue by ilovedesert001** [streamich/react-use#107]
since update to react 16.8.2
useSetState doesn't work

https://streamich.github.io/react-use/?selectedKind=State%2FuseSetState&selectedStory=Demo&full=0&addons=1&stories=1&panelRight=0

**Comment by ilovedesert001** [comment]
and this works fine

```typescript
const useSetState = <T extends object> (initialState: T = {} as any): [T, (patch: Function | Partial<T>) => void] => {
  const [state, set] = useState(initialState)
  const setState = (patch) => {
    if (patch instanceof Function) {
      set((prevState) => {
        return Object.assign({}, state, patch(prevState))
      })
    } else {
      const newState = Object.assign({}, state, patch)
      set(newState)
    }
  }
  return [state, setState]
}
```

**Comment by streamich** [comment]
Thanks for reporting this! Should be fixed now.

**Comment by ilovedesert001** [comment]
it seems still some bugs ... 

maybe this way is better

typescript

```
export const useSetState = <T extends object> (initialState: T = {} as any): [T, (patch: Function | Partial<T>) => void] => {
  const [tick,setTick] = useState(true)

  const [state, set] = useState<T>(initialState);
  const setState = patch => {
    if (patch instanceof Function) set(prevState => Object.assign(prevState, patch(prevState)));
    else set(Object.assign(state, patch));
    setTick(!tick)
  };
  return [state, setState];
}
```

**Comment by ilovedesert001** [comment]
> and this works fine
> 
> ```ts
> const useSetState = <T extends object> (initialState: T = {} as any): [T, (patch: Function | Partial<T>) => void] => {
>   const [state, set] = useState(initialState)
>   const setState = (patch) => {
>     if (patch instanceof Function) {
>       set((prevState) => {
>         return Object.assign({}, state, patch(prevState))
>       })
>     } else {
>       const newState = Object.assign({}, state, patch)
>       set(newState)
>     }
>   }
>   return [state, setState]
> }
> ```

This will cause problems when Passing state (Object) to child Components

**Comment by streamich** [comment]
> This will cause problems when Passing state (Object) to child Components

Can you give an example? Is it because child components mutate the state object?

**Comment by ilovedesert001** [comment]
check out these

[what i expect](https://codesandbox.io/s/pj53qylrjm)

[this may cause problems](https://codesandbox.io/s/zrx3qn1y54)

**Comment by likun7981** [comment]
@ilovedesert001 Why do you use `useRef`,  [The returned object will persist for the full lifetime of the component](https://reactjs.org/docs/hooks-reference.html?#useref).  So a subsequent change is invalid. `demo1` is expected, because you assign the patch to state, not create a new object. In fact the state point still has `not changed`.
![image](https://user-images.githubusercontent.com/13427467/53160835-b0c4cc80-3603-11e9-8c0c-346b967b2203.png).  

So in fact there is no need to use the `ref`
[work fine demo](https://codesandbox.io/s/r57ok7ylz4)

**Comment by ilovedesert001** [comment]
@likun7981 
In my case , I don't want to change state point (Or state Object), just need change state property to cause rerender.

@streamich 
Q:Is useSetState designed to change the state point (replaced by new  state object), or  persist state object for the full lifetime of the component ?

**Comment by likun7981** [comment]
@ilovedesert001 Every time, the `state` is a new point(object)

https://codesandbox.io/s/zl1wjo69qx

**Comment by streamich** [comment]
@likun7981 I think [this](https://github.com/streamich/react-use/pull/112) should be ti.

**Comment by likun7981** [comment]
> @likun7981 I think [this](https://github.com/streamich/react-use/pull/112) should be ti.

These two problems is no relationship

**Comment by streamich** [comment]
@likun7981 OK, sry.
