### ISSUE TITLE
useRafLoop should pass the timestamp from requestAnimationFrame

### ISSUE THREAD

**Issue by phosphene47** [streamich/react-use#1090]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Pass the timestamp argument from `requestAnimationFrame` to the callback of `useRafLoop`.

**Describe alternatives you've considered**
Just call `requestAnimationFrame` myself which really defeats the purpose of this library.

**Comment by phosphene47** [comment]
Thanks!

**Comment by xobotyi** [comment]
@phosphene47 note that whole hook changed.
Read the docs again pls, there are some breaking changes.
