### ISSUE TITLE
Improving the typing of useAsyncFn

### ISSUE THREAD

**Issue by foucdeg** [streamich/react-use#1111]
**Is your feature request related to a problem? Please describe.**

Since #589 was merged we can type the arguments of async functions passed to useAsyncFn.
But not quite perfectly yet:

In order to make the following code pass type-checking:

```typescript
// @ts-ignore
useAsyncFn(async (pad: Pad, sentence: string) => {
  await doStuff(pad, sentence);
});
```

I have to transform it the following way, wrapping my arguments in an object passed as the first arg:

```typescript
interface Arg {
  pad: Pad;
  sentence: string;
}

useAsyncFn(async (...args: Arg[]) => {
  const { pad, sentence } = args[0];
  await doStuff(pad, sentence);
});
```

This seems to be due to the fact that https://github.com/streamich/react-use/pull/589/files#diff-8cd4968b81985f0efc2053eabc37db6dR7 imposes that `args` extends `any[]` which requires the function to accept:

- any number of args (0-n)
- all args are of the same type.

**Describe the solution you'd like**

I'd like to be able to pass functions with any type and number of arguments to useAsyncFn and enforce these arguments.

**Describe alternatives you've considered**

**Workaround 1** as above:

```typescript
interface Arg {
  pad: Pad;
  sentence: string;
}

useAsyncFn(async (...args: Arg[]) => {
  const { pad, sentence } = args[0];
  await doStuff(pad, sentence);
});
```

**Workaround 2** without wrapping in an object, all args have the same type:

```typescript
type Arg = Pad | string;

useAsyncFn(async (...args: Arg[]) => {
  const [pad, sentence] = args;
  await doStuff(pad as Pad, sentence as string); 
});
```

**Comment by foucdeg** [comment]
If anyone is interested I've created a wrapper hook for Workaround 1:

```typescript
import { useAsyncFn } from 'react-use';

/**
 * A wrapper around useAsyncFn until its arguments can be properly typed
 * See https://github.com/streamich/react-use/issues/1111
 *
 * @param callback to be called in useAsyncFn
 * @param deps that should trigger recreating the callback
 */
/* eslint-disable-next-line @typescript-eslint/no-explicit-any */
export function useTypedAsyncFn<T>(callback: (input: T) => Promise<any>, deps: any[]) {
  return useAsyncFn(async (...args: T[]) => {
    await callback(args[0]);
  }, deps);
}
```

**Comment by benneq** [comment]
@foucdeg I think this is resolved. Could you please check again and close this issue?

```
const [state, fetch] = useAsyncFn(async (n: number, s: string) => {
  // ...
});

fetch(); // err: Expected 2 arguments, but got 0.ts(2554)
fetch("foo", 42); // err: Argument of type 'string' is not assignable to parameter of type 'number'.ts(2345)
fetch(42, "foo"); // works
```

**Comment by foucdeg** [comment]
It is indeed, thanks!
