### ISSUE TITLE
useMount does not call destructor

### ISSUE THREAD

**Issue by testarossaaaaa** [streamich/react-use#1112]
**What is the current behavior?**
useMount does not call destructor, but should be, because it pretends to be the shortest version of useEffect with empty deps.

This link show the difference between useMount and useEffect:
https://codesandbox.io/s/shy-shape-sswz7

**What is the expected behavior?**
Like useEffect, it must call the destructor (if returned value is a function). For example, to unsubscribe from a subscription created in the useMount handler.

**Comment by xobotyi** [comment]
It does not pretend to be shortest version of `useEffect`.

If you'd read the docs, you see that `useMount` is called only on mount, if ypou need cleanup you should use `useLifecycles` hook
