### ISSUE TITLE
useLocalStorage does not update value when key change

### ISSUE THREAD

**Issue by nicgirault** [streamich/react-use#1147]
**What is the current behavior?**

When the key of the local storage change with the same hook, the initialisation is not run.

**Steps to reproduce it and if possible a minimal demo of the problem.

https://codesandbox.io/s/practical-almeida-13o7o?file=/src/App.tsx

**What is the expected behavior?**

When the key change, the initial value is set

**A little about versions:**  

see code sandbox

**Comment by betoharres** [comment]
for me it's not updating at all, I just switched to the conventional window.localStorage and everything is working just fine

**Comment by nspaeth** [comment]
@nicgirault @betoharres 
Can you see if #1025 Fixes this issue?

**Comment by dsgriffin** [comment]
There are still issues with this hook not syncing correct values when watching the same key in multiple components
