### ISSUE TITLE
Why use `as const` in useHash.

### ISSUE THREAD

**Issue by introfei** [streamich/react-use#1220]
**I define a custom hook function named useScannerInput. Typescript throw a error when call the function. I   change my code form ` return [scannerValue, setScannerValue];` to ` return [scannerValue, setScannerValue] as const;` refer to how this use in useHash. And solved this error, but I don't konw why.**

```
//Function define
const useScannerInput = ({
  selector,
  onEnter
}: any) => {
  const [scannerValue, setScannerValue] = React.useState<string>('');

  React.useEffect(() => {
    const dom = document.querySelector(selector);
    const cleanUpScannerEvent = dom ? scannerEventListener(dom as HTMLElement, onEnter, setScannerValue) : null;

    return () => {
      if (cleanUpScannerEvent) {
        cleanUpScannerEvent();
      }
    };
  }, [onEnter, selector]);

  return [scannerValue, setScannerValue];
};
```
```
//Function call
const [scannerValue, setScannerValue] = useScannerInput({
    selector: '#scannerInput',
    onEnter: addSku
  });
setScannerValue('');

TS2349: This expression is not callable.
Not all constituents of type 'string | Dispatch<SetStateAction<string>>' are callable.
Type 'string' has no call signatures.
``

**Comment by whinc** [comment]
without `as const`, typescript will treat element of return array as  union type of every element type of return array. with `as const`, typescript will treat return array as a tuple, in other word every element in return array will keep it's type.
e.g.
```typescript
const arr1 = [100, '100']
type T1 = typeof arr1 // (number | string)[]

const arr2 = [100, '100'] as const
type T2 = typeof arr2 // readonly [100, '100']
```

**Comment by introfei** [comment]
> without `as const`, typescript will treat element of return array as union type of every element type of return array. with `as const`, typescript will treat return array as a tuple, in other word every element in return array will keep it's type.
> e.g.
> 
> ```ts
> const arr1 = [100, '100']
> type T1 = typeof arr1 // (number | string)[]
> 
> const arr2 = [100, '100'] as const
> type T2 = typeof arr2 // readonly [100, '100']
> ```

thanks.
