### ISSUE TITLE
[useMeasure] ref has wrong type

### ISSUE THREAD

**Issue by axelboc** [streamich/react-use#1264]
**What is the current behavior?**

The code below errors:

```tsx
const [ref] = useMeasure();
return <div ref={ref} />
```

```
Type 'UseMeasureRef<HTMLElement>' is not assignable to type 'string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.
  Type 'UseMeasureRef<HTMLElement>' is not assignable to type '(instance: HTMLDivElement | null) => void'.
    Types of parameters 'element' and 'instance' are incompatible.
      Type 'HTMLDivElement | null' is not assignable to type 'HTMLElement'.
        Type 'null' is not assignable to type 'HTMLElement'.  TS2322
```

Reproduced in: https://codesandbox.io/s/purple-bash-btzpp?file=/src/App.tsx

**What is the expected behavior?**

Type `UseMeasureRef<E>` should be `(instance: E | null) => void`, though React's built-in `RefCallback<T>` type could probably be used as well.

**A little about versions:**  
- _React_: 16.13.1
- `@types/react`: 16.9.35
- _`react-use`_: 15.1.1
- _Did this work in the previous package version?_ Yes, for sure in 13.27.1

**Comment by jas0ncn** [comment]
Same issue, is there any progress? 🤔

**Comment by wdfinch** [comment]
Any updates on this?

**Comment by Dreamacro** [comment]
You can override the default generics (`<E extends HTMLElement = HTMLElement>`).

```typescript
const [ref] = useMeasure<HTMLDivElement>()
```

**Comment by axelboc** [comment]
If I'm not mistaken, you'd have to use `const [ref] = useMeasure<HTMLDivElement | null>()`, which is exactly the problem. The generic is meant to narrow down the type of the element that will receive the ref function. You shouldn't have to specify `null`, and `useMeasure()` should, by default, return a `ref` function with a type that React agrees with.

**Comment by axelboc** [comment]
Happy New Year! 🎉 

I still can't upgrade `react-use` because of this issue. Bypassing the error with a cast is not trivial and super ugly, and `const [ref] = useMeasure<HTMLDivElement | null>()` doesn't actually work because `HTMLDivElement | null` doesn't extend `HTMLElement`, as per the definition of the generic.

I've just rebased the PR on `master`: https://github.com/streamich/react-use/pull/1267.

**Comment by axelboc** [comment]
Hi @robinvw1, I notice you've recently broaden the type of `useMesaure`'s generic from `HTMLElement` to `Element` to support SVG elements. Would you have time to take a look at this issue as well, by any chance? I've rebased the PR, so we just need someone to review it and merge it: #1267

**Comment by JoeDuncko** [comment]
Hi all! [@react-hookz/web](https://github.com/react-hookz/web), the new library by one of `react-use`'s former maintainers (background [here](https://github.com/streamich/react-use/issues/1872) and [here](https://github.com/streamich/react-use/issues/1974)) has [a new implementation of `useMeasure`](https://react-hookz.github.io/web/?path=/docs/sensor-usemeasure--example) that I think solves this problem.

For those interested, there's an official [migration guide for migrating from react-use to @react-hookz/web](https://react-hookz.github.io/web/?path=/docs/migrating-from-react-use--page). 

Hope this helps!

**Comment by ahmafi** [comment]
`useIntersection` has the same problem!

**Comment by elogrus** [comment]
> `useIntersection` has the same problem!

up
