### ISSUE TITLE
useScroll doesn't work at all in Gatsby (tried on a fresh install)

### ISSUE THREAD

**Issue by michelecocuccio** [streamich/react-use#1290]
**What is the current behavior?**
It just returns 0 for both x and y and it doesn't do anything

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

https://codesandbox.io/s/prod-violet-kc6qo?file=/src/pages/index.js (go to the :8000 tab)

**What is the expected behavior?**
To return the actual x and y value of the element with the ref

**A little about versions:**  
- _OS_: macOS Catalina
- _Browser (vendor and version)_: Chrome Version 83.0.4103.97
- _React_: 16.12.0
- _`react-use`_: useScroll

**Comment by Khalidxx** [comment]
I'm facing the same problem when using with Gastby. Did you find a solution @michelecocuccio ?

**Comment by michelecocuccio** [comment]
@Khalidxx It worked for me in the end but it's not what I was looking for. I was trying to use it on the body but it wasn't the correct use.
