### ISSUE TITLE
I translate the demo into Chinese

### ISSUE THREAD

**Issue by zenghongtu** [streamich/react-use#130]
I think you can add it to the readme.😊

[react-use-chinese]( https://github.com/zenghongtu/react-use-chinese)

**Comment by streamich** [comment]
That's cool! We can definitely add a link to the readme.

My only concern is how will you sync the changes in the future if it is in a different repo?

**Comment by streamich** [comment]
Added a link to readme. Please check if it is correct (I'm not sure which version of Chinese that is).

**Comment by zenghongtu** [comment]
> My only concern is how will you sync the changes in the future if it is in a different repo?
> 
> I guess, you could `npm install react-use`, so you have the latest hooks, and then maintain the `/src/__story__` and `/docs` folders.

yeah
