### ISSUE TITLE
Allow message parameter of useBeforeUnload to be a function

### ISSUE THREAD

**Issue by thdk** [streamich/react-use#1332]
**Is your feature request related to a problem? Please describe.**
The hook useBeforeUnload registers an event when a component that uses that hooks is rendered for the first time. The isDirty parameter can be a function but the message parameter currently is not. So the message is set once unless you rerender the component.

**Describe the solution you'd like**
I would like to suggest the following signature for useBeforeUnload
```
const useBeforeUnload = (
	enabled: boolean | (() => boolean) = true,
	message?: string | (() => string)
) => {
...
}
```

**Describe alternatives you've considered**
I've used a local state `const [beforeUnloadMessage, setBeforeUnloadMessage] = useState(defaultMessage);` but this caused the component to rerender only to display a different beforeUnloadMessage in case the user would navigate away.

I can send you a PR for this.

Related to #842

**Comment by kachkaev** [comment]
Given that [custom message is no longer supported by most browsers](https://stackoverflow.com/a/38880926), should we just mark the `message` arg  as `@deprecated`? Supporting function value and even asking the devs to provide any value does not seem worthy these days. The result won’t be seen by most users anyway.

Somewhat related PR: #1673

**Comment by thdk** [comment]
That's indeed what I've also discovered after logging this issue.

Closing this in favor of #1673
