### ISSUE TITLE
react-universal-hooks - use custom hooks in class

### ISSUE THREAD

**Issue by salvoravida** [streamich/react-use#134]
https://github.com/salvoravida/react-universal-hooks

Hi!

Could be usefull, if you need a custom Hook in your class component without refactor ...

your feedback would be appreciated!

**Comment by wardoost** [comment]
`react-universal-hooks` seems to override react exports which doesn't feel like the right way to implement this. I think the approach discussed in https://github.com/streamich/react-use/issues/597 is cleaner and more versatile.
