### ISSUE TITLE
Conflict between the use createStateContext and createReducerContext hooks and exhaustive-deps lint rule

### ISSUE THREAD

**Issue by tamakisquare** [streamich/react-use#1380]
**What is the current behavior?**
The functions, `setState` and `dispatch`, associated with `createStateContext` and `createReducerContext` hooks, respectively, are flagged by the **exhaustive-deps** lint rule when they are used in hooks such as `useEffect` and not being included in the dependency arrays.

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`.**

Here is a link to screenshots that showcase the issue. I took the demo code of the `createStateContext` hook taken from the official docs and added a simple `useEffect` to demonstrate the issue. 
[Screenshots](https://imgur.com/a/9GgKfvG)

**What is the expected behavior?**
According to the official React docs ([reference](https://reactjs.org/docs/hooks-reference.html)), the `setState` and `dispatch` functions returned from `useState` and `useReducer` hooks have stable identity and thus are safe to exclude them from the dependency array. In fact, the exhaustive-deps lint rule does not flag `setState` and `dispatch` functions associated with `useState` and `useReducer` hooks when they are omitted from the dependency array. 

The `setState` and `dispatch` functions resulted from `createStateContext` and `createReducerContext` should be compatible with the exhaustive-deps lint rule in the same way.

**A little about versions:**  
- _OS_: MacOS 10.15.5
- _Browser (vendor and version)_: 
- _React_: v16.13.1
- _`react-use`_: v15.3.2
- _Did this worked in the previous package version?_

**Comment by dcporter** [comment]
> The setState and dispatch functions resulted from createStateContext and createReducerContext should be compatible with the exhaustive-deps lint rule in the same way.

Is that possible to do?

**Comment by tamakisquare** [comment]
After a second thought, I think it's right how the lint rule applies as it is. Although the original `useState` and `dispatch` functions are designed to have stable identities, the `useState` and `dispatch` functions associated with `createStateContext` and `createReducerContext` are in fact context objects, which are mutable and thus cannot be viewed as stable.
