### ISSUE TITLE
Inferred TypeScript template type for createBreakpoint?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [streamich/react-use#1399]
**Is your feature request related to a problem? Please describe.**
When you use `createBreakpoint`, the return type of the function it creates is a general `string`. That can be problematic in TypeScript consumers with `noImplicitAny` enabled because the general `string` type cannot be used to index an object with a known set of keys and no index signature.

_(too much TypeScript jargon? see this [playground example](https://www.typescriptlang.org/play/#code/PTAEGEHsBtIJwM6gJZIIagNYDtIHdtQAXATwAcBTUPZIgC2LqswpKQHI4KATd0NbN1AAjaAFcK7AFABjSNgRFQc2IlABeUAG9QXbgC5QABgA0I8RUMBGUAF8A3FKkhQAFTqoUCbOyVposHg8KISKcMgySgC2kNxUwhQyaGIIVAAGLCRpypBi0EIJ-NgkoGHI2ADmoBQAbhRwJs5g0MgsoOzsZvDtaAjcAGadRUK4SgBWKUqcPHzd7KIS0v1i2JHI8qAVFERQqgAykJCpABSZhmWVAJTaUqB3utticIQq8AgA2pkAuo62Ti7uTyefrleKJZKpRhUUiUUCQfpQrCsLxw7BUeGInD4Qg1fzIITyCgIKTLVZEdaELY7GDwACq2App1YhmmvFAAB92gtJNctLd7lwiE8XjTEJ9WD8pH8mm4mKA0jCKPDspBKHA0ERuuVEYrSmwiBQoptkHUkPRoeR0QiMHAVuSoujhGNEkRHC5zfLMsq4WqNd0KiaiYj-IFgpkEIYmFwzKy+Jz5hYlis1hsqbt4ABpVjwpkkQxehGKjGvRC8-l3QXCnKqD7fX5SIA))_

**Describe the solution you'd like**
We can change `createBreakpoint` to have a template type for its input that `extends Record<string, number>` and have its function return a `keyof` that type.

```ts
const createBreakpoint<Breakpoints extends Record<string, number>>(
  breakpoints: Breakpoints = { laptopL: 1440, laptop: 1024, tablet: 768 }
) => () => {
```

There might be some more type massaging that needs to be done internally to make TypeScript happy... I haven't looked too deeply.

**Describe alternatives you've considered**
```ts
const useBreakpoint = createBreakpoint(breakpoints) as () => keyof typeof breakpoints;
```

**Comment by armand1m** [comment]
I've opened this PR related to this issue quite a while ago, but I'm not sure if it is ever getting merged https://github.com/streamich/react-use/pull/2240

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues I no longer have context on. If anybody else is still seeing this, I'd encourage you to file a new issue with more information. Cheers!
