### ISSUE TITLE
Full IE11 support

### ISSUE THREAD

**Issue by michellocana** [streamich/react-use#140]
First of all, **thank you for this package**, it has been very useful for my projects!
I've noticed the production build it's not fully compatible with IE11. 
I managed to do a "manual tree-shake" using `babel-plugin-transform-imports`, but i still get errors on IE11 using some hooks, e.g:

```js 
// ...
// production build of useWindowSize, IE11 won't be able to destructure this
const [state, setState] = react_1.useState({
  width: isClient ? window.innerWidth : initialWidth,
  height: isClient ? window.innerHeight : initialHeight,
});
// ...
```
My question is: can we add a `.browserslistrc` on the package, so we can get full support for older browsers in the production build?

**Comment by streamich** [comment]
I think we can simply set TypeScript target to ES5 here:

- https://github.com/streamich/react-use/blob/master/tsconfig.json#L3

```json
{
  "target": "es5"
}
```

**Comment by michellocana** [comment]
Oh, much simpler than i thought, thanks for the quick reply 🚀
