### ISSUE TITLE
Couldn't find package "@xobotyi/scrollbar-width@1.9.5"when I executed "yarn add react-use"

### ISSUE THREAD

**Issue by Bruce-zxy** [streamich/react-use#1426]
**What is the current behavior?**
`
[1/4] 🔍  Resolving packages...
error Couldn't find package "@xobotyi/scrollbar-width@1.9.5" required by "react-use" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`
![image](https://user-images.githubusercontent.com/22904758/89518847-13b51e00-d80e-11ea-8d15-1969c6b2bb44.png)

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**
none
**What is the expected behavior?**
Install it
**A little about versions:**  
- _OS_: Mac OS 10.15.6
- _Browser (vendor and version)_: Chrome 84.0.4147.105
- _React_: 16.10.0
- _`react-use`_: 15.3.3
- _Did this worked in the previous package version?_ no

**Comment by xobotyi** [comment]
Maybe there is something with your network or someething.

Because
a) i cant reproduce it
b) here is the package: https://www.npmjs.com/package/@xobotyi/scrollbar-width

**Comment by Bruce-zxy** [comment]
This is really weird, it is normal for me to install other packages.

![Uploading image.png…]()

**Comment by Bruce-zxy** [comment]
I started the proxy, but it still doesn't work

![image](https://user-images.githubusercontent.com/22904758/89521102-7cea6080-d811-11ea-949c-3a8fff2cc800.png)

**Comment by JaLe29** [comment]
Same for me (via npm).


```
... % npm i react-use
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@xobotyi%2fscrollbar-width - Not found
npm ERR! 404 
npm ERR! 404  '@xobotyi/scrollbar-width@1.9.5' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-use'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     ..../.npm/_logs/2020-08-06T10_15_16_304Z-debug.log
```

![image](https://user-images.githubusercontent.com/22296816/89524885-9d042a80-d7e5-11ea-8484-c45629579cb4.png)

**Comment by xobotyi** [comment]
Looks like something phappening to npm registry.
Because from time to time i get "service unavailable" messages from its frontend.
Also i have no issues even after dropping yarn's cache 🤔 Looks like npm's problems also affects it's CDN

**Comment by xobotyi** [comment]
To be fair i'm also unable to reach https://registry.npmjs.org/@xobotyi%2fscrollbar-width

**Comment by xobotyi** [comment]
Welp yeah. looks like it is a cloudflare issue again

**Comment by JaLe29** [comment]
@xobotyi I agree, definitely problem with npm, not related to this package.

**Comment by Amadey666** [comment]
[npm problem](https://status.npmjs.org/) 😕

**Comment by JaLe29** [comment]
Looks like it is working now.

Thx for the best lib guys.

**Comment by Bruce-zxy** [comment]
It works now.

![image](https://user-images.githubusercontent.com/22904758/89600782-6ab20600-d895-11ea-8238-692aeab03104.png)

**Comment by Bruce-zxy** [comment]
Thx.
