### ISSUE TITLE
What is doing "!."?

### ISSUE THREAD

**Issue by SkutinAnton** [streamich/react-use#1452]
https://github.com/streamich/react-use/blob/985c8b4a5b98a76755bc84275c503f1c0b2a2f4e/src/useFullscreen.ts#L27

**Comment by xobotyi** [comment]
uhh.. maybe typescript docs could help you? 🤨
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator

**Comment by SkutinAnton** [comment]
Oh, thank you 😊  I didn’t see that it was typeScript and I was looking in ECMAScript docs.
