### ISSUE TITLE
[Maybe bug] use-css component twinkles

### ISSUE THREAD

**Issue by zhaoyao91** [streamich/react-use#147]
Some of my pages and components use `use-css` to style, but when I switched to them, them would always twinkle at first, without styles and become normal in the next flash.

version: react-use 5.7.1

**Comment by streamich** [comment]
I've switched `useEffect` for `useLayoutEffect` in #151 should be out in [`5.8.1`](https://github.com/streamich/react-use/releases/tag/v5.8.1)

Do you still see the flash? Could you post a reproducible example?

**Comment by zhaoyao91** [comment]
@streamich I don't known, since I have switched to use emotion.sh to style our app.

**Comment by streamich** [comment]
OK, thanks, then I will close this for now.
