### ISSUE TITLE
useBreakpoint always returns the smallest breakpoint while it's calculating the width

### ISSUE THREAD

**Issue by ekawatani** [streamich/react-use#1493]
**What is the current behavior?**
`useBreakpoint` always returns the smallest breakpoint for the first time it runs regardless of the actual screen size. This is very inconvenient because if code renders different UI based on this breakpoint then it first renders the UI for a small screen, and then immediately switches to the UI for a larger screen. This makes the UI to flash for a brief moment.

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**
https://codesandbox.io/s/vigilant-hamilton-xhtn4?file=/src/App.js

**What is the expected behavior?**
The expected behavior is that it returns `undefined` until the widow width is calculated. This way, the consumer code can wait until the actual breakpoint is provided.

**A little about versions:**  
- _OS_: All browsers
- _Browser (vendor and version)_: All browsers
- _React_: latest
- _`react-use`_: latest
- _Did this worked in the previous package version?_ No

**Comment by dcporter** [comment]
(Or seems reasonable to return the actual current value, since it’s statically measurable without side effects)

**Comment by ekawatani** [comment]
That's a good idea. Is this fixable by just setting the initial value of  `screen` to `window.innerWidth` instead of `0`? That sounds like an easy change.

https://github.com/streamich/react-use/blob/master/src/createBreakpoint.ts#L6
