### ISSUE TITLE
useMountedState doesn't seem to work properly in SSR(Nextj.js)

### ISSUE THREAD

**Issue by nghiepit** [streamich/react-use#1549]
**What is the current behavior?**

On SSR(Next.js) app the `isMounted()` always is `false`.

```jsx
import { useMountedState } from "react-use";

export default function IndexPage() {m
  const isMounted = useMountedState();

  console.log(isMounted());

  return <div>{isMounted() ? "mounted" : "loading...."}</div>;
}
```

**Reproduction**
https://codesandbox.io/s/eloquent-feistel-xj1iw?file=/pages/index.js

**What is the expected behavior?**
Render properly both client-side and server-side.

**A little about versions:**  
- _React_:  16.13.1
- _`react-use`_:  15.3.4

**Comment by n4bb12** [comment]
I think the problem is that the hook doesn't re-render when the mounted state changes:
https://github.com/streamich/react-use/blob/master/src/useMountedState.ts#L8

**Comment by xobotyi** [comment]
@n4bb12 well it should not =)
@nghiepit since `useMountedState` does not cause component re-render your example works as it should.

**Comment by n4bb12** [comment]
I would say it's surprising when something called `useXState` doesn't re-render when X changes. That is contrary to how useState works.

> well it should not =)
Is that an opinion or a reason?

**Comment by n4bb12** [comment]
I see now that the hook is used by multiple other ones that seem to rely on it not re-rendering.

Would you be open to an additional hook that re-renders on mount change?

**Comment by xobotyi** [comment]
The only usecase for `isMounted`  - not to set another state if component is already unmounted while any callback performed.

1) I dont understand the sense of using `useMountedState` since while render is done component will be rendered so treat it as mounted, if you need to run some actions there is `useEffect` and `useMount`. If component is unmounted - there will be no re-renders so noone will know that component is unmounted.
2) If `useMountedState` would be a conventional statefull hook callbacks that run asynchroniously will never know that components is unmounted, since `isMounted` would be just a const.

**Comment by xobotyi** [comment]
@n4bb12 atm i agree uhat i should have called it somewhat differently, but we have what we have and hook can be renamed some time later as for now i'll only add annotation to the description that this hook does not re-render on state change.

**Comment by n4bb12** [comment]
Thanks for elaborating. That's perfect. Should I add a short sentence to the docs?

**Comment by n4bb12** [comment]
Just some more details why this happens

- There is only an issue in a server-side-rendering context. Client-side seems to be perfectly fine, I also see it working on the storybook.
- `useEffect` is not called on the server, so the first client-side render uses `state.current = false`.
- After first render the `useEffect` gets executed and state.current is now true, but does not re-render the component.

If a component wants to display different client/server components, or initialize appearance on the client, it doesn't work (e.g. for SEO reasons you might want an accordion to be expanded in the server response but be collapsed on the client).

**Comment by xobotyi** [comment]
>Should I add a short sentence to the docs that this does not re-render?

@n4bb12 no thanks ill add it manually.
