### ISSUE TITLE
Can useTitle be used in react-navigation?

### ISSUE THREAD

**Issue by Larva02** [streamich/react-use#1621]
Can useTitle be used in react-navigation?
![Image 137](https://user-images.githubusercontent.com/12692666/98227876-cbcf9f80-1f92-11eb-9be3-366efdda30f5.png)

**Comment by Larva02** [comment]
import React from 'react';
import {Button, Text, View} from "react-native";
import useTitle from 'react-use/lib/useTitle';
const UseHookTest = () => {
    useTitle('Hello world2!');
    return (
        <View>
            <Text>useTitle...</Text>
        </View>
    )
}
export default UseHookTest

It doesn't work！

**Comment by luisgurmendezMLabs** [comment]
I don't think that the useTitle hook is meant for something else than react for web. If you want to change the title of a screen you could probably build your own hook for that! 
Some kind of combination of this:

```
function useNavigationTitle(title:string){
   const navigation = useNavigation();
   navigation.setOptions({ title: title });
}
```

and the actual useTitle hook https://github.com/streamich/react-use/blob/master/src/useTitle.ts if you want to store the last title and set it once your component unmounts

**Comment by Larva02** [comment]
I just think all use hooks methods can be used in react native. Thank you for your explanation
