### ISSUE TITLE
Typescript 4.1.2 fails with "Cannot find name 'PositionError'"

### ISSUE THREAD

**Issue by syabro** [streamich/react-use#1646]
**What is the current behavior?**
I've got an error
```
node_modules/react-use/lib/useGeolocation.d.ts(11,21): error TS2304: Cannot find name 'PositionError'.
```

react-use: 15.3.4
typescript: 4.1.2

**Comment by dovidweisz** [comment]
I'm running into the same issue.

My `node_modules` folder is listed in my tsconfig `excludes`

I also tied adding: 

`node_modules`
`node_modules/react-use`
`node_modules/react-use/lib/useGeolocation.d.ts`

still failing

**Comment by dovidweisz** [comment]
I just wonder if maybe this is an issue with TypeScript and not with the types.

**Comment by dovidweisz** [comment]
It seems like `PositionError` was changed to `GeolocationPositionError` in this version of Typescript.

**Comment by dovidweisz** [comment]
The fix itself is easy, and I would gladly do a PR for it. The issue is backwards compatibility with older versions of Typescript.

I did a little research and there doesn't seem to be a good solution to this problem.

For the time being i created a patch and am running it postinstall.

Here's the patch (it's not that pretty, but it should work): https://gist.github.com/dovidweisz/4d76168339db89cf05e1090a84b7ee41

**Comment by giogonzo** [comment]
@dovidweisz [typesVersions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions) could help here?

**Comment by ileonovdima** [comment]
resolve problem  add global.d.ts 

type PositionError = GeolocationPositionError;

**Comment by dovidweisz** [comment]
@giogonzo Cool, I didn't know that was available. (I wonder how it would be implemented)

@ileonovdima Super cool TYVM

**Comment by giogonzo** [comment]
@dovidweisz basically producing 2 different outputs (e.g. one in lib and one in lib4.1) and applying your patch only on lib4.1 (and pointing TS to the correct folder via that key in package.json)

**Comment by dovidweisz** [comment]
> @dovidweisz basically producing 2 different outputs (e.g. one in lib and one in lib4.1) and applying your patch only on lib4.1 (and pointing TS to the correct folder via that key in package.json)

## Hmmmm

Seems doable, but I would flip that around. I would:

1.  Upgrade the library to the latest version of  Typescript.
1. Add a build step that copies the `d.ts` into a `ts4.0` directory, and...
1. Applies the reverse of my patch with a simple string replacement (`src.replace("GeolocationPositionError", "PositionError")`) to the original files.


I'm looking for other projects with the same (or similar) issues. I guess any front end project that is _built_ in Typescript.

**Comment by giogonzo** [comment]
> Seems doable, but I would flip that around

I agree 👍

**Comment by ranisalt** [comment]
> solved the problem by adding in global.d.ts

Where should this file go? I tried several places and typescript doesn't seem to pick it up.

**Comment by ValentinH** [comment]
> > solved the problem by adding in global.d.ts
> 
> Where should this file go? I tried several places and typescript doesn't seem to pick it up.

Same here

**Comment by dovidweisz** [comment]
I have it working, it's in my /sec file.

**Comment by cliffordfajardo** [comment]
I'm also getting this with typescript v4.1.3

**Comment by xobotyi** [comment]
@dovidweisz made a bit overkill the easiest way is to introduce own interface compatible with GeolocationPositionError
