### ISSUE TITLE
Changelog is full of repeating entries

### ISSUE THREAD

**Issue by dlindenkreuz** [streamich/react-use#1653]
What is going on there? v15.3.4 has like >100 repeated entries 🤯 

https://github.com/streamich/react-use/blob/master/CHANGELOG.md

**Comment by xobotyi** [comment]
wow!
Looks like semanticrelease-changelog issue. Our changelogs generated automatically from commit messages so they're not hand-written.

**Comment by dlindenkreuz** [comment]
Seems to be fixed now.
