### ISSUE TITLE
useAsync should keep last value when loading again.

### ISSUE THREAD

**Issue by xitianfz** [streamich/react-use#172]
Currently useAsync would set its `state.value` to `undefined` when initiate another loading. This is sometimes inconvenient when used in codes as below. It makes the Table empty during the loading instead of showing old data.

```jsx
const dataLoader = useAsync(...)

return (
  <Table data={dataLoader.value} loading={dataLoader.loading} />
)
```

Is it possible to keep last value when loading again?

**Comment by wardoost** [comment]
I agree, the other case where you don't want to display old data while loading could still be done like this

```js
const dataLoader = useAsync(...)

return (
  <Table
    data={dataLoader.loading ? undefined : dataLoader.value}
    loading={dataLoader.loading}
  />
)
```

Or you could do the loading check in your `Table` component

**Comment by wardoost** [comment]
We could use `useSetState` instead of `React.useState` to manage `useAsync`'s internal state so that it always returns a `value`, `loading` and `error` keys. Or is there a reason for not returning a state of the same shape every time?

**Comment by oliverviljamaa** [comment]
Agreed, we ended up creating a custom hook for this behaviour.

**Comment by streamich** [comment]
Closing as this seems old issue. Feel free to re-open.
