### ISSUE TITLE
Feature request: useUpdateLayoutEffect

### ISSUE THREAD

**Issue by adesurirey** [streamich/react-use#1756]
**Is your feature request related to a problem? Please describe.**
Cannot use `useUpdateEffect` to run effects before painting

**Describe the solution you'd like**
A new `useUpdateLayoutEffect` acting the same as `useUpdateEffect` but using `useLayoutEffect`

**Describe alternatives you've considered**
Passing an option to `useUpdateEffect` 

Let me know what you think, I may have time write this new hook.

**Comment by omwagh28** [comment]
Assign me this issue

**Comment by adesurirey** [comment]
@omwagh28 this library is not maintained anymore
