### ISSUE TITLE
useKeyPressEvent miss a way to call preventDefault()

### ISSUE THREAD

**Issue by PlanetIrata** [streamich/react-use#176]
- [x] Generic event subscription hook `useEvent(event, target = window)`
- [x] Create simple `useKey` hook ~~`useKeyDown` and `useKeyUp` hooks~~.
- [x] Split the `useKeyPress` hook into two:
  - [x] `useKeyPress` &mdash; native implementation, that uses `useKeyDown` and `useKeyUp`.
  - [x] `useKeyboardJs` &mdash; one that uses `keyboardjs` package. (It could also use internally `useAsync` hook for loading the `keyboardjs` dependency.)
- [x] `useKeyPressEvent` would receive `useKeyPress` or `useKeyPressKeyboardJs` as an argument.
- [x] Everywhere through this hook chain events are passed along so the end user has access to them.

---

*original:*

Hi! When using useKeyPressEvent to detect a press on Escape, if the browser's window is maxed under MacOS, the Safari window is un-maxed:

```
useKeyPressEvent("escape", (param) => {
  console.log("Esc pressed!");

  // the maximized Safari window will be un-maxed.

  // param contains "escape", would be better
  // if we could receive the event to call param.preventDefault();
});

```

**Comment by streamich** [comment]
Yeah, that's a shame currently those `useKeyPress` and `useKeyPressEvent` hooks swallow the events and you don't have access to them.

I general I would refactor both of those hooks as follows:

- [ ] Create simple `useKeyDown` and `useKeyUp` hooks.
- [ ] Split the `useKeyPress` hook into two:
  - [ ] `useKeyPress` &mdash; native implementation.
  - [ ] `useKeyPressKeyboardJs` &mdash; one that uses `keyboardjs` package.
- [ ] `useKeyPressEvent` would receive `useKeyPress` or `useKeyPressKeyboardJs` as an argument.
- [ ] Everywhere through this hook chain events are passed along so the end user has access to them.

**Comment by JesseFarebro** [comment]
@streamich the same goes for `useClickAway`. The event should be passed through to the callback so users can call `preventDefault` or utilize the event how they see fit.

**Comment by streamich** [comment]
@JesseFarebro done!

**Comment by DaleSalcedo** [comment]
@streamich can you explain how we can use the event to call `preventDeafult` for example?  I don't see anything in the docs that show the event being passed
