### ISSUE TITLE
useAsync causes an infinite refresh loop when used with a local variable as parameter

### ISSUE THREAD

**Issue by nirga** [streamich/react-use#1761]
**What is the current behavior?**

When using `useAsync` with a local variable as a parameter, it causes an infinite refresh loop on the browser. Not sure if that's by design because of how react is built or not, but if so we should probably document it.

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

```js
function useDoStuff() {
  const data = [1, 2, 3];
  return useAsync(() => {
    return Promise.resolve(new_data.map((x) => x + 1));
  }, [data]);
}

function App() {
  const data = useDoStuff();

  return (
    <div>
      {data.loading ? (
        <div>Loading...</div>
      ) : data.error ? (
        <div>Error: {data.error.message}</div>
      ) : (
        <div>Value: {JSON.stringify(data.value)}</div>
      )}
    </div>
  );
}
```

**What is the expected behavior?**

Browser should not hang and it should be able to render the view correctly without constantly trying to refresh.

**A little about versions:**  
- _OS_: Mac OS 11
- _Browser (vendor and version)_: Chrome 87
- _React_: 17.0.1
- _`react-use`_: 15.3.8
- _Did this worked in the previous package version?_ Not sure

**Comment by poalrom** [comment]
This is the default behavior of most react hooks. They compare dependencies by references, not by value, so each time it's a new array. Just stabilize reference to the array (by saving it inside the state or by another way) and it will work fine

**Comment by nirga** [comment]
Thanks! Does it mean that all deps must always be a result of a `useState`?
