### ISSUE TITLE
[V17] ReferenceError: navigator is not define (Next.js)

### ISSUE THREAD

**Issue by nghiepit** [streamich/react-use#1777]
**What is the current behavior?**
After upgrade to `17.0.0` from `15.3.8`
> ReferenceError: navigator is not define
> node_modules/react-use/lib/useNetworkState.js:5:11)

**Steps to reproduce:**
https://codesandbox.io/s/red-cookies-yyq9f?file=/pages/index.js

**What is the expected behavior?**
Just work again on Next.js.

**A little about versions:**  
- _OS_: macOS
- _Browser (vendor and version)_: 
- _React_: 17.0.1
- _`react-use`_: 17.0.0
- _Did this worked in the previous package version?_
`15.3.8`

**Comment by xobotyi** [comment]
@nghiepit recheck please with 17.0.1 is it back to normal?

**Comment by nghiepit** [comment]
Wow too quickly.
Tks @xobotyi  it works again.
