### ISSUE TITLE
Typescript problem with types in useMeasure()

### ISSUE THREAD

**Issue by nghiepit** [streamich/react-use#1781]
**What is the current behavior?**
```jsx
const [ref, { height }] = useMeasure<HTMLDivElement>();
```
Compile time error
> Property 'height' does not exist on type '(() => void) | Pick<DOMRectReadOnly, "left" | "right" | "bottom" | "top" | "x" | "y" | "height" | "width">'

**Reproduction:**
https://codesandbox.io/s/billowing-haze-oqxdg?file=/src/App.tsx

**What is the expected behavior?**
Without missing type error message.

**A little about versions:**  
- _`react-use`_:  17.0.1
- _`typescript`_:  4.1.3
- _Did this worked in the previous package version?_ `15.3.8`

**Comment by mdugue** [comment]
same here. The problem seems to be that an array is returned whilst a **tuple** would be needed. @streamich should I provide a PR to fix it?

**Comment by nghiepit** [comment]
I've just seen the PR https://github.com/streamich/react-use/pull/1780

**Comment by mdugue** [comment]
here we go: https://github.com/streamich/react-use/pull/1782 @streamich

**Comment by mdugue** [comment]
@nghiepit damn, I oversaw that one. It does the same as mine but mine is a bit more general purpose, so maybe we should go with that one 😅
