### ISSUE TITLE
New Hook: useRequest

### ISSUE THREAD

**Issue by jzhao62** [streamich/react-use#1826]
currently we have useAsync, useAsyncFn, useAsyncRetry, but it would be better to wrap all 3 into a generic hook 

const {data, loading} = useRequest

User can just use this hook to resolve async api calls 

The idea of this feature comes from a hook library whose trend is growing very fast

https://hooks.umijs.org/hooks/async

**Comment by Svish** [comment]
I feel dealing with request life-cycles is maybe better left to the already existing, and very good [react-query](https://github.com/tannerlinsley/react-query) or [swr](https://github.com/vercel/swr)?

**Comment by jzhao62** [comment]
yeah i think so
