### ISSUE TITLE
[react-use] Error when run app

### ISSUE THREAD

**Issue by rikainhatnguyen** [streamich/react-use#1845]
**What is the current behavior?**
The code below error:
```
import { useMeasure } from 'react-use';
```
- run `yarn` -> `tsc` is OK
- run app `yarn start` is error

```
node_modules/react-use/lib/useGetSet.d.ts(3,82):
',' expected.  TS1005

    1 | import { Dispatch } from 'react';
    2 | import { IHookStateInitAction, IHookStateSetAction } from './misc/hookState';
  > 3 | export default function useGetSet<S>(initialState: IHookStateInitAction<S>): [get: () => S, set: Dispatch<IHookStateSetAction<S>>];
```

**What is the expected behavior?**
Run app without the error

**A little about versions:**  
- _React_: 16.13.1
- "@types/react": "^16.9.0",
- _`react-use`_: 17.1.1

Who can help me to give any idea?

**Comment by alex-windett** [comment]
Also getting this error, downgrading to `^15.3.4` works for me, however, thats a few versions back

**Comment by liambowers** [comment]
Similar issue but I'm not able to actually install it:

```
../../node_modules/react-use/lib/useGetSet.d.ts:3:82 - error TS1005: ',' expected.

3 export default function useGetSet<S>(initialState: IHookStateInitAction<S>): [get: () => S, set: Dispatch<IHookStateSetAction<S>>];
                                                                                   ~

../../node_modules/react-use/lib/useGetSet.d.ts:3:96 - error TS1005: ',' expected.

3 export default function useGetSet<S>(initialState: IHookStateInitAction<S>): [get: () => S, set: Dispatch<IHookStateSetAction<S>>];
```

* `react`: 16.13.1
* `react-use`: 17.1.1

**Comment by hekkim** [comment]
I think it's a problem because tsc does not recognize [labeled tuple](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements).
After I update typescript@^4.x.x, it does not cause the error anymore.

Please try it after update your typescript version

**Comment by Zertz** [comment]
If for whatever reason you can't upgrade TypeScript, you can avoid typechecking dependencies:

```json
{
  "compilerOptions": {
    "skipLibCheck": true
  }
}
```

**Comment by xobotyi** [comment]
@rikainhatnguyen @alex-windett  @liambowers just use TS 4.x.x.
Labeled tuples are part of TS spec introduced in TS 4

**Comment by piavgh** [comment]
> ```json
> skipLibCheck
> ```

This does not work

**Comment by piavgh** [comment]
> If for whatever reason you can't upgrade TypeScript, you can avoid typechecking dependencies:
> 
> ```json
> {
>   "compilerOptions": {
>     "skipLibCheck": true
>   }
> }
> ```

This does not work

**Comment by piavgh** [comment]
> Also getting this error, downgrading to `^15.3.4` works for me, however, thats a few versions back

This works for me, because I'm not allowed to upgrade typescript to v4
