### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by dy** [streamich/react-use#187]
Just `yarn add react-use` and got

```sh
Module not found: Can't resolve 'keyboardjs' in 'C:\projects\ACQ-Portal\node_modules\react-use\esm'
```

**Comment by dy** [comment]
Same for 
```sh
Module not found: Can't resolve 'rebound' in 'C:\projects\ACQ-Portal\node_modules\react-use\esm'
```

**Comment by scottc11** [comment]
also getting this.

**Comment by nino-moreton** [comment]
Also getting exactly
`Module not found: Can't resolve 'keyboardjs' in 'C:\[myprojectname]\node_modules\react-use\esm'`

**Comment by streamich** [comment]
`rebound` and `keyboardjs` are [now in `peerDependencies`](https://github.com/streamich/react-use/blob/master/package.json#L46-L47) and have to be installed separately, as some people were complaining about the large bundle size.

**Comment by Kosai106** [comment]
@streamich A bit tedious but I understand the reasoning for this.

**Comment by wardoost** [comment]
I added a peer dependency note to the `useKeyboardJs` docs and aligned the `useSpring` docs with it. Less should run into this issue now.

**Comment by soosap** [comment]
These errors also appear when using `useMouse` as well.

If i use `import useMouse from 'react-use/lib/useMouse'` then these errors are not thrown. They appear the moment I use the following import style: `import { useMouse } from 'react-use'`.

Is there a way to fix the error for the latter import style?

**Comment by wardoost** [comment]
@soosap The error will show up no matter what hook you are importing. As far as I know there are 2 ways to avoid the error and use the `import { useMouse } from 'react-use'` import style:

1. Install peer dependencies or
1. Use a babel transform plugin as described in https://github.com/streamich/react-use/issues/102#issuecomment-475909523

**Comment by vinkla** [comment]
I'm also seeing this error even when I'm only importing `useTitle`:

```javascript
import { useTitle } from 'react-use';
```

**Comment by chandlervdw** [comment]
Happens with `useScroll`, too. While it works, @vinkla's fix shouldn't have to be the case.

**Comment by wardoost** [comment]
@vinkla Methods of importing are documented in the [usage section in the readme](https://github.com/streamich/react-use#usage). This question seems to come back a lot though. Any suggestions how this can be documented better? Or a fix would even be better of course @chandlervdw?

**Comment by vinkla** [comment]
@wardoost I guess what I found confusing was that one could use both named imports or with the full path. Though, in my case I wasn't able to import `useTitle` without the fullpath.
