### ISSUE TITLE
Session Storage, storage source of truth

### ISSUE THREAD

**Issue by luisgurmendezMLabs** [streamich/react-use#1874]
**Is your feature request related to a problem? Please describe.**
Wouldn't it make more sense that the useSessionStorage have the session storage as source of truth? I found it confusing that it relies on a useState to keep track of the storage state
**Describe the solution you'd like**
By having a listener inside the useSessionStorage hook, it will be possible to use several hooks to the same portion of the storage

**Comment by JoeDuncko** [comment]
It's pretty normal for the state to be the source of truth for things like this.

Have you considered using react context alongside `useSessionStorage` to achieve what you are looking to do?

**Comment by luisgurmendezMLabs** [comment]
Didn't need to! It was unnecessary to listen to the same storage state at the end

**Comment by egemon** [comment]
So basically my issue, when I am using this hook in two different places and see that one doesn't change another is result of this?
