### ISSUE TITLE
Typescript Error in `useGetSety.d.ts`

### ISSUE THREAD

**Issue by kennycrosby** [streamich/react-use#1879]
**What is the current behavior?**

In create-react-app with typescript getting the following error:

```
TypeScript error in /node_modules/react-use/lib/useGetSet.d.ts(3,82):
',' expected.  TS1005

    1 | import { Dispatch } from 'react';
    2 | import { IHookStateInitAction, IHookStateSetAction } from './misc/hookState';
  > 3 | export default function useGetSet<S>(initialState: IHookStateInitAction<S>): [get: () => S, set: Dispatch<IHookStateSetAction<S>>];
```

Try using `useWindowScroll` in create react app with typescript

`"typescript": "^3.7.5"`

**What is the expected behavior?**

**A little about versions:**  
- _React_: `"react": "^16.13.1",`
- Typescripe: `"typescript": "^3.7.5"`
- _`react-use`_: latest

**Comment by xobotyi** [comment]
Use TS version 4+
