### ISSUE TITLE
`useScroll` expects a single ref argument.

### ISSUE THREAD

**Issue by ardyfeb** [streamich/react-use#1920]
**What is the current behavior?**
```tsx
 const wrapper = useRef<HTMLDivElement>()
 const scrollable = useScroll(wrapper)
```

throwing error on development, but its still works

**What is the expected behavior?**
Not throwing error.

https://github.com/streamich/react-use/blob/master/src/useScroll.ts#L13 is checking `typeof ref.current === 'undefined'`. `ref.current` is always undefined until the ref component mounted

**A little about versions:**  
- _OS_: Manjaro Arch Linux
- _Browser (vendor and version)_: Opera (74.0.3911.218)
- _React_: 17.0.2
- _`react-use`_: 17.2.1

**Comment by mantagen** [comment]
In order for `wrapper` to be a valid `RefObject` (and not `undefined`), you need to instantiate it with `null`, so you code would be:
```ts
  const wrapper = useRef<HTMLDivElement>(null)
  const scrollable = useScroll(wrapper)
```
