### ISSUE TITLE
Usenetwork API usage error, import Usenetwork error

### ISSUE THREAD

**Issue by wmx-us** [streamich/react-use#1921]
Usenetwork API usage error, import Usenetwork error

Attempted import error: 'useNetwork' is not exported from 'react-use'.

This is my import file: Ask for help to look at the problem
import {useSetState,useNetwork} from  'react-use'

**Comment by xobotyi** [comment]
It has been renamed to `useNetworkState` in v17

**Comment by wmx-us** [comment]
oh ,
Thank you very much.
