### ISSUE TITLE
useSetState does not have a callback like this.setState

### ISSUE THREAD

**Issue by hugobarragon** [streamich/react-use#1922]
**What is the current behavior?**

useSetState on docs says its the same as this.setState but i cant pass a callback to run after the state has changed

https://reactjs.org/docs/react-component.html#setstate

**What is the expected behavior?**

useSetState possible to pass a callback to run after state changed

**A little about versions:**  
- _OS_: Windows10
- _Browser (vendor and version)_: Version 89.0.4389.114 (Official Build) (64-bit)
- _React_: 16.12.0
- _`react-use`_: 17.2.2
- _Did this worked in the previous package version?_ no

**Comment by xobotyi** [comment]
There is no sense to mimic the callbacks within hooks paradigm. `useEffect`exists for these purposes.

**Comment by hugobarragon** [comment]
the problem is that useEffect will run on every state change and not on a single state mutation

**Comment by xobotyi** [comment]
As i said i dont think that setState callbacks should be implemented and it is definely not a bug.

You are free to create PR and in case enyone will support the change - ill merge.

**Comment by hugobarragon** [comment]
> As i said i dont think that setState callbacks should be implemented and it is definely not a bug.
> 
> You are free to create PR and in case enyone will support the change - ill merge.

ok thanks, i will open a PR then
