### ISSUE TITLE
typo in useGetSet type declaration leads to a typescript error in npm run build

### ISSUE THREAD

**Issue by MaximDelyukin** [streamich/react-use#1952]
**What is the current behavior?**
typescript build in CRA (npm run build) fails with error:
 `export default function useGetSet<S>(initialState: IHookStateInitAction<S>): [get: () => S, set: Dispatch<IHookStateSetAction<S>>];`
I see that there is extra ">" symbol in the end of the string which is a typo.
The file is node_modules/react-use/lib/useGetSet.d.ts(3,82)
**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**
1) npm install react-use
2) run npm run build

**What is the expected behavior?**
no build errors
**A little about versions:**  
- _OS_: 
- _Browser (vendor and version)_: 
- _React_: 
- _`react-use`_: 17.2.3
- _Did this worked in the previous package version?_

**Comment by danielingegneri** [comment]
```
TypeScript error in /project/node_modules/react-use/lib/useGetSet.d.ts(3,82):
',' expected.  TS1005
```
Real path above is replaced with `/project`

react-use: 17.2.3
npm: 6.14.12
node: v10.19.0
react-scripts: 3.2.0
typescript: 3.9.9

**Comment by xobotyi** [comment]
@danielingegneri update your TS to 4+ to support named tuples.

**Comment by xobotyi** [comment]
@MaximDelyukin everything is fine with brackets, most liely you have TS version below 4, and in fails to compile named tuples

**Comment by danielingegneri** [comment]
Thanks will do that

**Comment by callmejm** [comment]
@xobotyi I using 4.5.0-dev.20210815 facing same issue

**Comment by LucaLJX** [comment]
@danielingegneri @xobotyi My TS version is 4.3.4 and facing the same issue.

![image](https://user-images.githubusercontent.com/16076854/129825913-5d4d4b33-0fa3-4445-ba50-9a807e215b66.png)

**Comment by LucaLJX** [comment]
> @danielingegneri @xobotyi My TS version is 4.3.4 and facing the same issue.
> 
> ![image](https://user-images.githubusercontent.com/16076854/129825913-5d4d4b33-0fa3-4445-ba50-9a807e215b66.png)

I reduced react-use version from 17.2.4 to 13.27.1,it works.

**Comment by Albert-ch** [comment]
@LucaLJX +1
