### ISSUE TITLE
useDeepCompareEffect

### ISSUE THREAD

**Issue by wardoost** [streamich/react-use#197]
React's useEffect hook, except using deep comparison on the inputs, not reference equality: https://github.com/kentcdodds/use-deep-compare-effect

Could possibly be done with other React hooks too?

**Comment by streamich** [comment]
Could be done, I would use [`react-fast-compare`](https://github.com/FormidableLabs/react-fast-compare) as a comparison function.

**Comment by wardoost** [comment]
Interesting, I see `react-fast-compare` is a fork of [`fast-deep-equal`](https://github.com/epoberezkin/fast-deep-equal). In the docs it state it handles React-specific circular references, like elements. I'm not sure why this would be needed in a hook?

**Comment by streamich** [comment]
`react-fast-compare` is as fast as `fast-deep-equal`, so you get that functionality for free.

It could be useful, when you you use React elements for comparison:

```js
const Demo = ({children}) => {
  useDeepCompareEffect(effect, [children]);
};
```
