### ISSUE TITLE
useLocalStorage fails to update during rehydration for Next

### ISSUE THREAD

**Issue by EthanStandel** [streamich/react-use#2052]
**What is the current behavior?**
If you init useLocalStorage or useSessionStorage in a Next app, the state gets lost during reydration.

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run 
```const [ state, setState ] = useLocalStorage("STORE_KEY", false); // <- in a Next app```
When there's a different value than `false` in localStorage for "STORE_KEY", Next SSR will send back false, but hydration will init the value to true.  So there's a state change without ever calling setState.  I would like to add a utility hook that can be utilized base on an option like "isSsr."  The utility hook could be something like this.

```
const useForceRerenderOnMount = (shouldRerender = true) => {
  const [, forceRerender] = useState(false);
  useEffect(() => {
    if (shouldRerender) {
      forceRerender(true);
    }
  }, []);
};
```

And then the utility hook can be utlized as `useForceRerenderOnMount(isSsr);` within the storage hooks.  And if this ticket makes it to this weekend, I'll throw up a PR with this 🙂

**What is the expected behavior?**
It'd be nice to at least have a flag or something to forceRerender.

**A little about versions:**  
- _OS_: MacOS
- _Browser (vendor and version)_: Chrome
- _React_: @latest
- _`react-use`_: @latest
- _Did this worked in the previous package version?_: No

**Comment by EthanStandel** [comment]
I recently discovered that this project is effectively abandoned so I'm going to move my interest into @react-hookz/web which was suggested by the last exiting maintainer.

**Comment by kunjee17** [comment]
@EthanStandel  when did this happen ? Any pointers or link?

>  recently discovered that this project is effectively abandoned

**Comment by EthanStandel** [comment]
@kunjee17 https://github.com/streamich/react-use/issues/1974
