### ISSUE TITLE
The library is not compatible with TypeScript 4.4

### ISSUE THREAD

**Issue by karol-majewski** [streamich/react-use#2056]
**What is the current behavior?**

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

1. Install latest TypeScript (`npm install typescript@beta`)
2. Build your project (make sure `skipLibCheck` is non-existent or `false` in your `tsconfig.json`)

The build will fail with the following errors in `node_modules/react-use/lib/usePermission.d.ts`.

- Cannot find name 'DevicePermissionDescriptor'.
- Cannot find name 'MidiPermissionDescriptor'.
- Cannot find name 'PushPermissionDescriptor'.

**What is the expected behavior?**

Project builds.

**A little about versions:**  
- _OS_: n/a
- _Browser (vendor and version)_:  n/a
- _React_: n/a
- _`react-use`_: `17.2.4`
- _Did this worked in the previous package version?_ In TypeScript 4.3, yes.

TypeScript 4.4 introduces breaking changes to `lib.d.ts`. Here's [the full list](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/). These interfaces are no longer part of the standard library.

**Comment by kachkaev** [comment]
Same here. @gelove (author of https://github.com/streamich/react-use/pull/421) do you have any ideas? 🙏

**Comment by kachkaev** [comment]
I searched for the missing types in the [TypeScript repo](https://github.com/microsoft/TypeScript) and found them in `lib/lib.webworker.d.ts`. So my immediate thought was to make this tweak in the project’s `tsconfig.json`:

```diff
-   "lib": ["es2020", "dom"],
+   "lib": ["es2020", "dom", "webworker"],
```

Unfortunately, this change introduced dozens of new errors like:

```
node_modules/typescript/lib/lib.dom.d.ts:25:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: EventListenerOrEventListenerObject, ImportExportKind, TableKind, ValueType, ExportValue, Exports, ImportValue, ModuleImports, Imports, name, HeadersInit, BodyInit, RequestInfo, BlobPart, DOMHighResTimeStamp, CanvasImageSource, MessageEventSource, ImageBitmapSource, OnErrorEventHandler, TimerHandler, PerformanceEntryList, ReadableStreamReader, ReadableStreamController, VibratePattern, AlgorithmIdentifier, HashAlgorithmIdentifier, BigInteger, NamedCurve, GLenum, GLboolean, GLbitfield, GLint, GLsizei, GLintptr, GLsizeiptr, GLuint, GLfloat, GLclampf, TexImageSource, Float32List, Int32List, GLint64, GLuint64, Uint32List, BufferSource, DOMTimeStamp, FormDataEntryValue, IDBValidKey, Transferable, ReadableStreamDefaultReadResult, BinaryType, CanvasDirection, CanvasFillRule, CanvasLineCap, CanvasLineJoin, CanvasTextAlign, CanvasTextBaseline, ClientTypes, ColorSpaceConversion, EndingType, IDBCursorDirection, IDBRequestReadyState, IDBTransactionMode, ImageOrientation, ImageSmoothingQuality, KeyFormat, KeyType, KeyUsage, NotificationDirection, NotificationPermission, PermissionName, PermissionState, PremultiplyAlpha, PushEncryptionKeyName, PushPermissionState, ReferrerPolicy, RequestCache, RequestCredentials, RequestDestination, RequestMode, RequestRedirect, ResizeQuality, ResponseType, ServiceWorkerState, ServiceWorkerUpdateViaCache, VisibilityState, WebGLPowerPreference, WorkerType, XMLHttpRequestResponseType
node_modules/typescript/lib/lib.dom.d.ts:3984:5 - error TS2374: Duplicate index signature for type 'number'.
node_modules/typescript/lib/lib.dom.d.ts:5227:5 - error TS2374: Duplicate index signature for type 'number'.
...
```

So clearly that’s not the right way forward 😅

**Comment by karol-majewski** [comment]
One possible solution ([used by React](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0a4d1a8094019f8b1a9dc12820123d2170dc7cd5/types/react/global.d.ts), amongst others) is to declare the missing interfaces as empty interfaces in the global scope.

```ts
declare global {
  interface DevicePermissionDescriptor {}
  interface MidiPermissionDescriptor {}
  interface PushPermissionDescriptor {}
}
```

If the users are running a version of TypeScript that bundles real definitions of these types, they will be merged, causing no harm.

If the users are missing these types, empty interfaces will make TypeScript compile anyway.
