### ISSUE TITLE
useCopyToClipboard

### ISSUE THREAD

**Issue by scottc11** [streamich/react-use#208]
Here is the version I am using at work.

```
const useCopyToClipboard = (timeout = null) => {

  const [success, setSuccess] = useState(false);

  const copyToClipboard = (text) => {

    if (typeof text == "string" || typeof text == "number" ) {
      const element = document.createElement('textarea'); // create textarea HTML element
      element.value = text;                               // add the text to be copied to the element
      document.body.appendChild(element);                 // add element to DOM
      element.select();                                   // select the text
      document.execCommand('copy');                       // execute copy command
      document.body.removeChild(element);                 // remove element from DOM
      setSuccess(true);
    }
    else {
      setSuccess(false);
      console.error(`Cannot copy typeof ${typeof text} to clipboard, must be a valid string or number.`);
    }
  }

  useEffect( () => {
    // if timeout given, set success to false
    if (timeout) {
      if (success) setTimeout( () => setSuccess(false), timeout);
    }
  }, [success])

  return [success, copyToClipboard];
}
```
use:
```
const myComp = () => {
  const [copiedToClipboard, copyToClipboard] = useCopyToClipboard();
  const myText = "hello!!!";
  return <div onClick={() => copyToClipboard(myText)}>{myText}</div>
}
```

I only suggest adding it to this library because it is kind of a wonky/hacky way of doing something which I expected to be simple. It also seems to be the standard approach for cross-browser support.

NOTE: I took the actual "copy to clipboard" code from this [HackerNoon Arcticle](https://hackernoon.com/copying-text-to-clipboard-with-javascript-df4d4988697f)  as well as this [stackoverflow  question](https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript).

**Comment by wardoost** [comment]
Really useful hook 👍

I generally use [`clipboard-polyfill`](https://github.com/lgarron/clipboard-polyfill) for this functionality so we could also reuse that library? Do you want to submit a PR for this @scottc11?

**Comment by scottc11** [comment]
thanks @wardoost, I'll submit a PR.

I looked into the clipboard-polyfill and we could for sure reuse that library, but would that mean we would have to add it as a dependancy?

**Comment by streamich** [comment]
Maybe it makes sense to inject `copy` functionality, so 3rd party library can be included, if needed.

```js
const copyDefault = () => {
      const element = document.createElement('textarea'); // create textarea HTML element
      element.value = text;                               // add the text to be copied to the element
      document.body.appendChild(element);                 // add element to DOM
      element.select();                                   // select the text
      document.execCommand('copy');                       // execute copy command
      document.body.removeChild(element);                 // remove element from DOM
};

const useCopyToClipboard = (timeout = null, copy = copyDefault) => {

  const [success, setSuccess] = useState(false);

  const copyToClipboard = (text) => {

    if (typeof text == "string" || typeof text == "number" ) {
      copy(text);
      setSuccess(true);
    }
    else {
      setSuccess(false);
      console.error(`Cannot copy typeof ${typeof text} to clipboard, must be a valid string or number.`);
    }
  }

  useEffect( () => {
    // if timeout given, set success to false
    if (timeout) {
      if (success) setTimeout( () => setSuccess(false), timeout);
    }
  }, [success])

  return [success, copyToClipboard];
}
```

**Comment by scottc11** [comment]
I was trying to think of a way of detecting if the polyfill exists, and if it does then use the polyfill, if not, use the "copyDefault" function. Any thoughts on that? I'll just submit the PR then y'all can edit it if need be

**Comment by wardoost** [comment]
@streamich I don't think it's a good idea to inject a `copy` functionality as the signature of the injected function can have different forms. For example injecting `navigator.clipboard.writeText` from the [clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) would not work with the above snippet as it is asynchronous. Besides the unpredictability of behaviour it would also make this hook not much more than a glorified `useToggle` as it's not doing much more than managing a boolean state.

@scottc11 The name of `clipboard-polyfill` is a bit confusing as it is more a shim than a polyfill. I have used that package before as it's the only one that also supports fallbacks for `readText` as far as I know. For this hook we don't need to read from the clipboard plus I have noticed issues in Safari so I think we should steer clear of the `clipboard-polyfill` package.

For projects that only required copying to clipboard I have used [`copy-to-clipboard`](https://github.com/sudodoki/copy-to-clipboard) before. This package is probably the best choice for fallbacks for this hook as it seems to have the best browser support for text copying and isn't a massive dependency. Writing our own fallbacks is probably not going to be better/smaller than this package.

One last question, why is there a timeout in #209 ?

**Comment by scottc11** [comment]
@wardoost for your first question, if the decision is to add a dependancy then `copy-to-clipboard` sounds like a good choice.

> why is there a timeout in #209 ?

I feel like a good UI will indicate to the user that the text has been copied to their clipboard via a small message or something along those lines, and then hide that message after a second or two. This gives the user some sanity if they need to keep copying it for what ever reason. But it could for sure be debated whether we handle that functionality in the hook, or if we leave it out and let an external timeout deal with that effect.

**Comment by wardoost** [comment]
@scottc11 An `onSuccess` callback parameter could allow users to trigger a timeout:

```js
const useCopyToClipboard = (options) => {
  const {onSuccess = () => {}} = options;
  const [success, setSuccess] = useState(false);

  const copyToClipboard = useCallback((value) => {
    if (typeof value === "string" || typeof value === "number" ) {
      copy(value);
      setSuccess(true);
      onSuccess();
    } else {
      setSuccess(false);
      console.error(`Cannot copy typeof ${typeof value} to clipboard, must be a valid string or number.`);
    }
  }, [])

  return [success, copyToClipboard];
}
```

so you could do the timeout callback like this:

```js
const [showSuccess, setShowSuccess] = React.useState(false);

useCopyToClipboard(() => {
  setShowSuccess(true);
  setTimeout( () => setShowSuccess(false), 2000);
})
```
Putting the `onSuccess` callback in an options object so it's more similar to other hooks like `useFullscreen` for example: https://github.com/streamich/react-use/blob/5b39ab5d24d9ecfbbfbd3f45abacd7a5015bdb18/src/useFullscreen.ts#L4-L14
