### ISSUE TITLE
official site breaks down  

### ISSUE THREAD

**Issue by percy507** [streamich/react-use#2128]
**What is the current behavior?**

My browser: Google Chrome v93.0.4577.82

![image](https://user-images.githubusercontent.com/18365078/133872028-c8df3092-00be-4335-b8dc-ae3d6667d14b.png)

**Comment by arronKler** [comment]
same

**Comment by owen-duncan-snobel** [comment]
^

**Comment by zyc95** [comment]
same

**Comment by Avivhdr** [comment]
+1

**Comment by krushna-sharma** [comment]
For now you change the ts-loader version to `"ts-loader": "8.3.0"` in package.json to make it work.

**Comment by diegoasanch-capicua** [comment]
Still down

**Comment by diegoasanch** [comment]
Still down

**Comment by naruepanart** [comment]
today
![streamich github io_react-use_](https://user-images.githubusercontent.com/33704769/135029767-a2474f50-a798-452c-b524-49cb975019b4.png)

**Comment by uunw** [comment]
same

**Comment by asif-simform** [comment]
same

**Comment by Yasir900aslam** [comment]
+1

**Comment by UCS-Kris** [comment]
Is this project still maintained?

**Comment by oallouch** [comment]
alive ?

**Comment by brickspert** [comment]
[ahooks](https://github.com/alibaba/hooks) may be another choice.

**Comment by kylemh** [comment]
https://github.com/streamich/react-use/issues/1974
