### ISSUE TITLE
[useLocalStorage]

### ISSUE THREAD

**Issue by rikusen0335** [streamich/react-use#2224]
**What is the current behavior?**
useLocalStorage sets string in string: Something like:
```ts
const [v, setv] = useLocalStorage("theme");

<button onClick={() => setv("black")}>set</button>
```
will set `"black"` to local storage, NOT `black`

As I expected, `localStorage.setItem("theme", "black")` will set `black`

They means `localStorage.getItem("theme") === '"dark"'` will return `true` but `localStorage.getItem("theme") === 'dark'` will return `false`.

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**
https://codesandbox.io/s/react-fw-react-use-localstorage-vpu4i

**What is the expected behavior?**

**A little about versions:**  
- _OS_: Windows 10 (But remotely connect to and develop on Fedora 34)
- _Browser (vendor and version)_: Chromiun Edge 95.0.1020.44 (64bit)
- _React_: 17.0.2
- _`react-use`_: 17.3.1
- _Did this worked in the previous package version?_ I think not, I haven't used this package yet.

**Comment by flaval** [comment]
That's the normal behaviour, as described here : https://github.com/streamich/react-use/blob/master/docs/useLocalStorage.md, data is serialized / deserialized before beeing sent / get back to / from local storage, and the default serializer and deserializer are `JSON.stringify` and `JSON.parse`. You can override serializer to not tranform data to JSON if you don't want tranform your data to string : https://codesandbox.io/s/react-fw-react-use-localstorage-forked-in97s?file=/src/App.tsx

**Comment by rikusen0335** [comment]
I understand, thanks!

**Comment by hishamfangs** [comment]
I don't understand why this is the default behaviour, it's extremely annoying and not all cases require strong JSON.
Also, we can always serialize deserialize JSON, this was never an issue.
