### ISSUE TITLE
EditorConfig require

### ISSUE THREAD

**Issue by maxzitron** [streamich/react-use#23]
@streamich I think it's good idea to put EditorConfig in this project to make sure all contributors have the same configuration and prevent unnecessary the code formatting change over each PR.

Cheers,
Max

**Comment by streamich** [comment]
Sure, what settings do you want to save there?

**Comment by maxzitron** [comment]
@streamich I have no preference, to be honest. Your current setting would be fine :)

**Comment by streamich** [comment]
I personally use VSCode and would probably commit its `.vscode` folder, but don't mind EditorConfig being here, too.
