### ISSUE TITLE
useHover not work when use fragment element

### ISSUE THREAD

**Issue by JunyWuuuu91** [streamich/react-use#2302]
**What is the current behavior?**

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:*https://codesandbox.io/s/small-sunset-r2ve0h?file=/src/App.js*

**What is the expected behavior?**
work success。

**A little about versions:**  
- _OS_: macos
- _Browser (vendor and version)_: chrome 98
- _React_:  17.0.2
- _`react-use`_: 17,3,2
- _Did this worked in the previous package version?_ No

**Comment by WongYuYe** [comment]
cause we do not support

**Comment by wardoost** [comment]
For hover event you need an HTML element to bind event listeners to. A fragment does not have a corresponding HTML element so you will have to use `div` element instead of a fragment.
