### ISSUE TITLE
Install hooks seperate from each other 

### ISSUE THREAD

**Issue by dennisfrijlink** [streamich/react-use#2520]
Hi, I love the amount of useful hooks `react-use` contains. Now I've seen you can install them easily with the npm-package `react-use` but it is not the smallest one and you'll never use all of the custom hooks in a project. Is it possible to install the hooks seperate from each other (like for example components in [Radix UI](https://www.radix-ui.com/)). 

Or is this not necessary because the hooks you don't import inside the project (React, Next, Remix or whatever React based project) are not included at build time?

**Comment by childrentime** [comment]
@dennisfrijlink The unused hooks will not be imported, so there's no need to worry.

**Comment by dennisfrijlink** [comment]
Good to know!. Thanks @childrentime
