### ISSUE TITLE
useMedia deprecated methods

### ISSUE THREAD

**Issue by RobertoSimonini1** [streamich/react-use#2526]
I have forked and cloned the repository to take a look at the 'useMedia' hook and I noticed that we're using methods matchMedia() .addListener() and matchMedia() .removeListener() which are deprecated.
 
Shouldn't we replace them with methods addEventListener() and removeEventListener()?

**Comment by rileyjshaw** [comment]
This appears to have been fixed in https://github.com/streamich/react-use/commit/e7379f088787cbf9274c1fc21d36061f04855e4c.
