### ISSUE TITLE
This library broken the old browser

### ISSUE THREAD

**Issue by vipcxj** [streamich/react-use#263]
`-> use-callbag -> callbag-subscribe@1.5.1`
The index.cjs.js contain code
``` javascript
const subscribe = (listener = {}) => source => { // line 3
   ...
}
```
this is horrible that lots of browser not support es6 directly.

**Comment by streamich** [comment]
This lib is [now transpiled down to ES5](https://github.com/streamich/react-use/commit/61382e310981fdc0891e455becbf3637703ddbe6), you should not have this error anymore. If you do, feel free to reopen.
