### ISSUE TITLE
useAsyncRetry ts error

### ISSUE THREAD

**Issue by SwordsmanYao** [streamich/react-use#270]
when I use useAsyncRetry, I got `[ts] Expected 4 arguments, but got 1.`

![E4NV~6}3}1532WN5$@M 1 J](https://user-images.githubusercontent.com/20725188/56718379-36ced200-6771-11e9-9053-cc29ec16296e.png)

and the generate d.ts file:
![DL YS~5NX_O1G_C 4`~JIET](https://user-images.githubusercontent.com/20725188/56718517-7e555e00-6771-11e9-8f37-6dd654db5e4b.png)

when I remove `readonly` , it works

**Comment by tpdewolf** [comment]
+1. Have the same issue. Reacts type `DependencyList` is `ReadonlyArray<any>`, which does work. Does anyone know why it's being converted to `readonly any[]`

**Comment by posgarou** [comment]
It's because the typings are being produced using TS 3.4.5.  The `readonly any[]` syntax was introduced in 3.4 (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html).

When compiled with 3.4, that line reads:

```typescript
declare const useAsyncRetry: <T>(fn: () => Promise<T>, deps?: readonly any[]) => {
}
```

When compiled with 3.3.1, it produces:

```typescript
declare const useAsyncRetry: <T>(fn: () => Promise<T>, deps?: ReadonlyArray<any>) => {
```

I checked, and `tsc` still runs correctly with TS v3.1.6.  Maybe it would be useful to downgrade to a lower version in development so the typings produced are compatible with most recent versions of TS?

**Comment by streamich** [comment]
> Maybe it would be useful to downgrade to a lower version in development so the typings produced are compatible with most recent versions of TS?

@posgarou are you suggesting to downgrade the TS version of `react-use`?

**Comment by posgarou** [comment]
> > Maybe it would be useful to downgrade to a lower version in development so the typings produced are compatible with most recent versions of TS?
> 
> @posgarou are you suggesting to downgrade the TS version of `react-use`?

@streamich , I see three options:

1. Downgrade the TS version.  This will produce typings compatible with lower TS versions.
2. Don't support anything but the last couple TS versions.
3. Generate multiple typings (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions).

(3) is the best option, but it's more of a pain to setup.  That said, I don't see much downside to (1).

**Comment by streamich** [comment]
@posgarou I like version (1).

**Comment by streamich** [comment]
As there are no complaints anymore, I'm going to close this. In the future if we have something similar, we may want to adopt (1).

**Comment by Toub** [comment]
@streamich a warning about minimal typescript version on the main README would be helpful!

**Comment by streamich** [comment]
@Toub we could mention that in README, but I'm not sure if that is necessary as you can easily find that info in `package.json`

- https://github.com/streamich/react-use/blob/8b3b312b0f0fbce42d7c666666efc76d0806b241/package.json#L106

**Comment by Toub** [comment]
Sure. 
The only reason would be because it is a quite recent version.

**Comment by Cyrus-d** [comment]
i have the same problem in `useDebounce.d.ts` and `useAsyncRetry.d.ts` files:

![Capture](https://user-images.githubusercontent.com/4041334/66934513-78b54280-f047-11e9-9dd8-b763a3ce0534.PNG)

the typescript version is 3.6.3.

i have to change the `readonly ` to `ReadonlyArray` every time installing or updating packages.

any suggestions would be greatly appreciated.
