### ISSUE TITLE
8.1.4 useClickAway fix is a breaking change

### ISSUE THREAD

**Issue by PlanetIrata** [streamich/react-use#271]
Hi, useClickAway was not working anymore in my app after upgrading to 8.1.4. This was due to the replacement of the "click" event by the tracking of ["mousedown", "touchstart"] in the hook. I solved the issue by adding a last parameter ["click"] to my useClickAway calls, but such breaking change should not occur in a minor upgrade, the default event tracked by the hook should have been let to "click" with an optional way to set it to "mousedown" & "touchstart". Furthermore, this is not yet documented at https://streamich.github.io/react-use/?path=/story/ui-useclickaway--docs.

Thanks

**Comment by streamich** [comment]
Thank you for reporting this and sorry for the inconvenience.

It was a bug fix in a sense that the previous implementation did not work on some mobile devices. I really wanted to release it as a breaking change and last moment decided to release it as a fix. Sorry for that.

I have added the [new parameter to docs](https://github.com/streamich/react-use/blob/master/docs/useClickAway.md#reference).
