### ISSUE TITLE
toggleSet?

### ISSUE THREAD

**Issue by episodeyang** [streamich/react-use#272]
Thanks for this great library!

I'm trying to maintain a set of objects. and I want three methods:

1. setting the set to a particular set.
2. add or remove a particular element depending on whether it is available in the set
3. emptying the set.

It seems this should be an effect in the library. Is there currently a one-liner way of achieving this with `react-use`?

**Comment by streamich** [comment]
I don't think there is a good way to do what you want with hooks in this library, but it is an interesting idea for a hook, say `useSet`. You could do something like this (not tested):


```js
import useUpdate from 'react-use/lib/useUpdate';

const useSet = (initialElements, deps = []) => {
  const set = useMemo(() => new Set(initialElements));
  const update = useUpdate();
  
  return [set, {
    add: (el) => {
      set.add(el);
      update();
    },
    has: (el) => set.has(el);
  }];
};
```
