### ISSUE TITLE
useAudio: paused instead of isPlaying

### ISSUE THREAD

**Issue by MajorBreakfast** [streamich/react-use#284]
Consider adding a `paused` property to the state and to remove the `isPlaying` property

Advantages:
- Symmetry with the HTML element's API
- `isPlaying` isn't precise: It can either mean that the audio is currently playing (which it does not in this case) or I could mean that the audio is currently playing or will play as soon as it loads (which it does in this case). This is probably also the reason why the property has been standardized as `paused`.

**Comment by Serchinastico** [comment]
I'm pretty sure this issue can be closed now 😄

**Comment by streamich** [comment]
yup, thanks

https://github.com/streamich/react-use/blob/master/src/util/createHTMLMediaHook.ts#L14
