### ISSUE TITLE
useQuery or useQueryParams

### ISSUE THREAD

**Issue by dpikt** [streamich/react-use#304]
Enhancement idea, looking for feedback.
This hook would return an object of parsed query params from the window location:

```js
// url: mysite.com?foo=bar&test=3

function MyComponent () {
   const { foo, test }  = useQueryParams()
    return (...)
}

// foo = 'bar' 
// test = 3
```

Parsing would default to something like `parse` from [query-string](https://github.com/sindresorhus/query-string), but would optionally allow custom function to be passed.

**Comment by streamich** [comment]
Interesting, but why should it be a hook vs just a function?

```js
function MyComponent () {
   const { foo, test }  = parseQueryParams()
    return (...)
}
```

**Comment by dpikt** [comment]
Hmm that's a good point. I think I was hoping to leverage `useMemo` to reduce the calculation time.

```js
function useQueryParams (parse=defaultParse) {
   const query = window.location.search
   return useMemo(() => parse(query), [ query ])
}
```

However the savings could be minimal since parsing the params probably isn't too expensive. And you could also just memoize a function with lodash `memoize` or similar.

I'll leave it up to you whether you think this is a good use case for a hook, feel free to close if you think it falls outside the use case!

**Comment by AlexandreAWE** [comment]
> Interesting, but why should it be a hook vs just a function?
> 
> ```js
> function MyComponent () {
>    const { foo, test }  = parseQueryParams()
>     return (...)
> }
> ```

We could say the same thing for useLocalStorage.

It could be interesting to implement useQueryParams like use LocalStorage.

```javascript
function MyComponent () {
   const [foo, setFoo]  = useQueryParams('foo');
}
```

**Comment by streamich** [comment]
@AlexandreAWE adding ability to set a param makes it more interesting. How do you  change a single param?

I'm thinking an interesting hook would be if this internally used [`useLocation`](https://github.com/streamich/react-use/blob/master/docs/useLocation.md) and return what `useLocation` returns on every location change, but also parsed query params and a method to change the location. That would basically be a the minimal React router.

```js
const Demo = () => {
  const [params: {foo, test}, goto] = useRoute();
  // ...
};
```

**Comment by AlexandreAWE** [comment]
Changing a single params could be problematic if you use a routing library.

Here is my current Typescript implementation of useQueryParams hook (using [History](https://www.npmjs.com/package/history) Library):

I also use [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams) to handle query params.

```typescript
export function useQueryParams(param: string, history?: History): [string, (value: string) => void] {
  const searchParams = new URLSearchParams(document.location.search);

  const [paramValue, setParamValue] = useState<string>(searchParams.get(param));

  function setParam(value?: string) {
    if (value !== null) {
      searchParams.set(param, value);
    } else {
      searchParams.delete(param);
    }

    if (history) {
      history.push({ search: searchParams.toString() });
    } else {
      document.location.search = searchParams.toString();
    }

    setParamValue(value);
  }

  return [paramValue, setParam];
}

**Comment by AlexandreAWE** [comment]
Nice ! Thank you !
