### ISSUE TITLE
useBattery doesn’t work – obsolete API

### ISSUE THREAD

**Issue by filipdanic** [streamich/react-use#308]
The [useBattey hook](https://github.com/streamich/react-use/blob/master/src/useBattery.ts) relies on `navigator.getBattery`, which is an [obsolete API.](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getBattery) It will work on Chrome, but not many other places.

There doesn’t seem to be anything that works across all browsers at the moment. Which is fine, but I wouldn’t expect a hook to break the entire app because of an implementation detail. 

E.g: https://codesandbox.io/s/sleepy-browser-jf2dg

Comparison:
![use_battery](https://user-images.githubusercontent.com/7009755/57966360-01249f80-7951-11e9-9c1e-46a069066842.png)

At a minimum, it should be noted in the docs. Ideally, the useBattery hook should check if `navigator.getBattery` is working first. It should return something like an object `{supported: false` if `navigator.getBattery` is unsupported.

**Comment by mqliutie** [comment]
Chrome on iOS doesn't support
