### ISSUE TITLE
useAsync: loading is false on mount

### ISSUE THREAD

**Issue by posgarou** [streamich/react-use#314]
Due to a change in v8.1, the behavior and typings of `useAsync` are no longer accurate.

https://github.com/streamich/react-use/commit/4b998d6e0834e29f366574d668dc361c50be7ef3#diff-8e6e0808e6745d8058a2f9cbd476172dR22

Before that commit, there was a guarantee that if `loading` was false, then either `error` or `value` was set on the state.  Since that commit, `loading` is now false at mount, but `error` and `value` are both undefined.

That means that the following code errors on mount, even though it passes type checks:

```typescript
function App() {
  const state = useAsync(getUsers, []);

  if (state.loading) {
    return <>...</>;
  }

  if (state.error) {
    return <>Something went wrong!</>;
  }

  return (
    <ul>
      {state.value.map((user, i) => (
        <li key={i}>{user.name}</li>
      ))}
    </ul>
  );
}
```

Here's an example: https://uegk4.codesandbox.io/

**Comment by NullVoxPopuli** [comment]
I just ran in to this as well

**Comment by NullVoxPopuli** [comment]
reverting back to 8.1.0 and `useAsyncCallback` fixes the misbehavior for me.
seems like the issue is with useAsyncFn somehow being incorrect / maybe the refactor didn't work quite right :-\
idk. haven't dove that deep into it

**Comment by NullVoxPopuli** [comment]
working on a fix here: https://github.com/streamich/react-use/pull/321

**Comment by NullVoxPopuli** [comment]
PR finished.
