### ISSUE TITLE
useAsyncFn: eslint warning

### ISSUE THREAD

**Issue by Yijun95** [streamich/react-use#318]
I have copied the useAsyncFn.js in my program but I find there are some eslint warnings.

![image](https://user-images.githubusercontent.com/19189763/58453359-647eb080-814d-11e9-8111-6447d4d94863.png)

It seems not correct written.How to solve it?

**Comment by NullVoxPopuli** [comment]
this should be resolved by #321
![image](https://user-images.githubusercontent.com/199018/58584559-85fe9b80-8224-11e9-9444-2b3f07c3de69.png)
