### ISSUE TITLE
Why no semver?

### ISSUE THREAD

**Issue by NullVoxPopuli** [streamich/react-use#320]
I was looking at this file: https://github.com/streamich/react-use/blob/v8.1.0/src/useAsyncCallback.ts (useAsyncCallback), changed the version/tag to [8.2.0](https://github.com/streamich/react-use/blob/v8.2.0/src/useAsyncCallback.ts), and useAsyncCallback doesn't exist anymore!

with semver, it should remain until v9. :-\

**Comment by streamich** [comment]
Must have been my mistake.
