### ISSUE TITLE
Leverage lodash for debounce, throttle, etc.

### ISSUE THREAD

**Issue by steida** [streamich/react-use#372]
It's solid and battle tested. react-use should only wrap it correctly. And because of https://github.com/streamich/react-use/issues/370, it will be easy to write 👍

**Comment by steida** [comment]
Look:

```ts
import { useMemo, useEffect } from 'react';
import { throttle } from 'lodash';

export const useThrottleFn = <T extends (...args: any) => any>(
  fn: T,
  ms = 1000,
) => {
  const throttledFn = useMemo(() => {
    return throttle(fn, ms);
  }, [fn, ms]);
  // This is must because fn can call setState.
  useEffect(() => {
    return () => {
      throttledFn.cancel();
    };
  }, [throttledFn]);
  return throttledFn;
};
```

**Comment by steida** [comment]
And useThrottle is super simple.

```ts
import { useState } from 'react';
import { useThrottleFn } from './useThrottleFn';

export const useThrottle = <T>(value: T, ms = 1000) => {
  const [throttledValue, setThrottledValue] = useState(value);
  const setThrottledValueThrottled = useThrottleFn(setThrottledValue, ms);
  setThrottledValueThrottled(value);
  return throttledValue;
};
```

**Comment by streamich** [comment]
@steida `lodash` throttle is like 300 lines of code, is there something lighter?

**Comment by steida** [comment]
300 lines of code are nothing

**Comment by danbriggs5** [comment]
Just wondering if it's a problem that the function won't be throttled if the functions deps change. For example:
```javascript
const [count, setCounter] = useState(0);
const foo = useThrottleFn(
	useCallback(() => {
		setCounter(count + 1);
	}, [count, setCounter]),
);
```
I don't think the throttler would work in this case. But I could be wrong!

**Comment by GeKorm** [comment]
Lodash throttle/debounce has features that I've found indispensable in dozens of projects but are absent from simple implementations. I think the 300 lines are justified. Some examples of things I couldn't live without:

- `maxWait` The maximum time func is allowed to be delayed before it's invoked
- Option for trailing or leading invocations
- Flushing and cancelling invocations

I actually found this issue by looking for a maxWait option. 

However, I'm not sure that including all the bells and whistles is in the scope of this package. It's nice to know that every react-use hook is simple and lightweight. A focused package called eg. "use-throttle" may be more justified to include the full implementation.

**Comment by streamich** [comment]
Current `useDebounce` implementation is a nifty one-line wrapper around `useTimeoutFn` hook. Hopefully it solves 99% of use cases, give it a try.

---

@danbriggs5 there is [this test case](https://github.com/streamich/react-use/blob/master/tests/useDebounce.test.ts#L104), hope it answers your question.
