### ISSUE TITLE
useIsomorphicLayoutEffect

### ISSUE THREAD

**Issue by streamich** [streamich/react-use#377]
https://github.com/reduxjs/react-redux/blob/master/src/hooks/useSelector.js#L14-L15

**Comment by aleclarson** [comment]
This implementation is broken in React Native, causing `useEffect` to always be used.

More info: https://github.com/reduxjs/react-redux/pull/1444

**Comment by aleclarson** [comment]
FWIW, I just published `react-layout-effect` as a solution.

https://www.npmjs.com/package/react-layout-effect

Maybe `react-use` should depend on and re-export it?

I'll add you as a maintainer if that's what you decide.
