### ISSUE TITLE
peerDependencies warnings are annoying 

### ISSUE THREAD

**Issue by d-asensio** [streamich/react-use#384]
Hello,

I've seen in #102 that you moved large dependencies to the peerDependencies section to avoid library size bloating.

This is not a terrible approach, but people not using the hooks which depend in those packages will always get a warning from yarn or npm about a missing peer dependency (keyboardjs and rebound).

Since this repository is a kind of kitchen sink of react hooks, I think that it would be much better to set up a lerna monorepo. Having one package per hook, that would allow to consume them separately, and having an option for getting them all.

My proposal would be (similar to lodash):

```js
// For a single hook
import useKey from 'react-use.key'

// For all the hooks
import { useKey } from 'react-use'
```

This way you can define `keyboardjs` and `rebound` just to the packages that directly depend from them.

I can submit a PR making it work, but I would like to hear your opinion about this structure first.

**Comment by streamich** [comment]
- How would releases be done? Currently this project uses `semantic-release` to publish NPM package and GitHub release automatically.
- What would you use for monorepo? Bolt, Lerna, Yarn Namespaces?
- What does dot `.` mean in `react-use.key`? Is it just a character just like any other character?
- I don't see `lodash` being a monorepo. It seems to me just allows you to import different files from same `lodash` package `var object = require('lodash/fp/object');`. This is the same what currently `react-use` does. Or am I missing something?
- Is it worth it? Maybe it is better to remove `keyboardjs` and `rebound` from peer dependencies? Maybe move those hooks out of this library?

**Comment by FredyC** [comment]
This is not only the problem of "annoying peerDependencies", but the fact it's not possible to `import { useX } from 'react-use'` without getting an error about missing `keyboardjs`.

I think the most appropriate way is removing peer deps AND to remove the import of affected hooks from `index.js`. It should be documented to specifically `import useKeyboardJs from 'react-use/lib/useKeyboardJs'`. Same for `useSpring`.

It's not ideal for sure, but at least a majority of users won't be bothered by it and those who need those hooks have to read docs more carefully.

**Comment by FredyC** [comment]
@streamich So what's your opinion on that? Got 4 👍 here. I could provide a PR if you agree with such an approach. It's quite annoying if we cannot use autoimport in VSCode because of those two peer libs.

**Comment by xsanda** [comment]
I would suggest they be made optional dependencies: it seems rather strange to be required to install a keyboard library in order to use this framework at all in react-native.

**Comment by wardoost** [comment]
@xsanda I think [optional dependencies](https://docs.npmjs.com/files/package.json#optionaldependencies) does not relate to peer dependencies? Correct me if I'm wrong.

I like the approach @FredyC is proposing. Improving dx for most users while having extra documentation for hooks with peer deps seems like a good trade-off 👍

**Comment by streamich** [comment]
Sorry, I missed this thread.

> @streamich So what's your opinion on that?

I like this idea.

> I could provide a PR if you agree with such an approach.

That would be great.

**Comment by FredyC** [comment]
@streamich PR Ready
