### ISSUE TITLE
useClickAway: callback event definition KeyboardEvent is not enough

### ISSUE THREAD

**Issue by tkrotoff** [streamich/react-use#393]
The TypeScript declaration for the [callback](https://github.com/streamich/react-use/blob/v9.4.1/src/useClickAway.ts#L8) is:

```TypeScript
onClickAway: (event: KeyboardEvent) => void
```

KeyboardEvent is not enough, it should be: `KeyboardEvent | TouchEvent | MouseEvent | ...` or more probably `UIEvent` and then the user should cast it to MouseEvent, KeyboardEvent... depending on the parameters he passed to useClickAway()

**Comment by streamich** [comment]
Yeah, and maybe even more broad than `UIEvent`. Maybe it should be `unknown`. With ability for user to set it.
