### ISSUE TITLE
double tap on useList with set and push does not have the full list

### ISSUE THREAD

**Issue by episodeyang** [streamich/react-use#396]
I have the following pattern: 

```jsx
  const [breadCrumb, {set, push}] = useList([fullPath]);
  function expand(dir, depth) {
    if (depth < breadCrumb.length) {
      set(breadCrumb.slice(0, depth + 1));
    }
    push(dir);
  }
```

I'm expecting the breadCrumb list to experience both the truncation as well as the push. but only the push result appears.

The hooks should add all operations in the same synchronous call. Am I missing anything?

Thanks!

**Comment by streamich** [comment]
Currently it is written such that you can only do one operation per re-render.
