### ISSUE TITLE
What do you think about this?

### ISSUE THREAD

**Issue by latteyo** [streamich/react-use#397]
I hope that useDarkMode is added to react-use.
---
Custom hook that changes background color when button is clicked

<pre>const useDarkMode = () => {
  const [darkMode, setDarkMode] = useState('light')

  const switchMode = () => {
    if (darkMode === 'light') {
      window.localStorage.setItem('theme', 'dark')
      setDarkMode('dark')
    } else {
      window.localStorage.setItem('theme', 'light')
      setDarkMode('light')
    }
  }

  useEffect(() => {
    const localTheme = window.localStorage.getItem('theme')
    if (localTheme) {
      setDarkMode(localTheme)
    }
  }, [])

  return [
    darkMode,
    switchMode,
  ]
}
</pre>

**Comment by streamich** [comment]
Would this work for you?

```js
import useLocalStorage from 'react-use/lib/useLocalStorage';

const useDarkMode = defaultTheme => useLocalStorage('theme', defaultTheme);
```

**Comment by latteyo** [comment]
Oh, I understand.
