### ISSUE TITLE
`useRefArray()` hook

### ISSUE THREAD

**Issue by d-asensio** [streamich/react-use#445]
What do you think about adding a hook to handle references of array like elements?

The code would look like this:

```javascript
const useRefArray = () => ({
  _refs: [],
  set current(ref) {
    this._refs.push(ref);
  },
  get current() {
    return this._refs;
  }
});
```

And a typical application could be the following:

> A list of items with smooth scrolling.

[![Edit ScrollToItem](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-star-uri0x?fontsize=14)

Should I submit a PR?, do you see any problem in the code above?

**Comment by streamich** [comment]
I'm not sure if I follow. The `useRefArray` is just a function, right? For it to be a hook, I think it has to use at least one of the React hooks internally.
