### ISSUE TITLE
useUpdate unnecessarily returns a new function each time

### ISSUE THREAD

**Issue by dcporter** [streamich/react-use#463]
`useUpdate` returns a new function object each time, but because you were smart and called its `setState` updater with a function, you don't need to.

Wrapping the returned function in a `useCallback` (with no options — the lint rule should be fine with it) would make the return value amenable for use inside other `useCallback`s (where it currently fails to `===` and creates a new callback each time).

**Comment by streamich** [comment]
Sounds like a plan.

**Comment by Belco90** [comment]
When https://github.com/streamich/react-use/pull/554/ is merged with tests for `useUpdate` I'm happy to take care of this one, should be easy to test too.
