### ISSUE TITLE
opencollective-postinstall is not friendly to Windows

### ISSUE THREAD

**Issue by stevefan1999-personal** [streamich/react-use#474]
```
.../node_modules/react-use postinstall$ opencollective-postinstall || true
│ 'opencollective-postinstall' is not recognized as an internal or external command,
│ operable program or batch file.
│ 'true' is not recognized as an internal or external command,
│ operable program or batch file.
└─ Failed in 169ms
```
So...is this intentional or what

**Comment by baldarian** [comment]
npm i -g opencollective-postinstall

**Comment by streamich** [comment]
Well, I don't think we should require installing anything globally. I currently using Mac and didn't have this problem, but we should fix it for Windows.

**Comment by xobotyi** [comment]
@stevefan1999-personal what Win version do you use? On win10 i have no problems..

**Comment by stevefan1999-personal** [comment]
@xobotyi You're probably using WSL/Git Bash if you didn't get a syntax error regarding the boolean

**Comment by xobotyi** [comment]
@stevefan1999-personal well, they're installed but i'm using `terminal`/`power shell`, so they can't actually affect.

**Comment by pmarshall** [comment]
opencollective-postinstall should be a dependency (not a dev-dependency) of react-use. Then it should work fine.

**Comment by xobotyi** [comment]
@pmarshall @stevefan1999-personal `reat-use` doesnt have `opencollective-postinstall` as dependency, only one dep has it - `husky`.
As for now they've changed the `postinstall` script to `opencollective-postinstall || exit 0` which is fine for windows of any version and this bug can be closed.

**Comment by robross0606** [comment]
> As for now they've changed the `postinstall` script to `opencollective-postinstall || exit 0` which is fine for windows of any version and this bug can be closed.

This still shows a visible error on Windows:
```

> husky@4.3.6 postinstall C:\Code\nl\node-server-utils\node_modules\husky
> opencollective-postinstall || exit 0

'opencollective-postinstall' is not recognized as an internal or external command,
operable program or batch file.
```
I doesn't recognize it as an error, but not exactly clean.

**Comment by LennyLip** [comment]
got following error with yarn install:
```
[4/4] Building fresh packages...
[7/12] ⡀ react-use
error C:\project\node_modules\react-use: Command failed.
Exit code: 1
Command: opencollective-postinstall || true
Arguments:
Directory: C:\project\node_modules\react-use
Output:
"opencollective-postinstall" �� ���� ����७��� ��� ���譥�
```

**Comment by LennyLip** [comment]
Finally, I fixed this issue by adding "c:\Program Files\Git\usr\bin\" to the PATH window environment variable. it contains a 'true' command that does no exist in plain windows cmd
