### ISSUE TITLE
[Suggestion] add CONTRIBUTING.md

### ISSUE THREAD

**Issue by PetterIve** [streamich/react-use#505]
I recently submitted a PR and when setting up the project locally I had some issues. Particularly related to yarn, I have no previous experience using it and had some issues with duplicated React types). 

I think a simple "get started" section in a CONTRIBUTING.md file would be most helpful :)

**Comment by Belco90** [comment]
Indeed, would be nice to have some guidelines about what's needed when adding new hooks (example file, test file, linting passing, etc) or when editing hooks (add new tests cases, etc)

**Comment by xobotyi** [comment]
@belco90 I'll write a contributing.md when I'll have some time.

**Comment by streamich** [comment]
One requirement for a hook could be:

- A hook internally must use at least one another hook.

**Comment by wardoost** [comment]
@streamich What exactly do you mean with the following?

> A hook internally must use at least one other hook

Do you mean a hook has to use a part of the React hooks API internally? This kind of seems like a given since this lib a collection custom hooks tbh. Unless there's a way to create hooks or hook factory functions without using React's API?

**Comment by streamich** [comment]
@wardoost Yes, exactly that. It is given, but I've seen people just write a JavaScript function that starts with `use...` and they think it is a hook. Maybe if it is obvious, we should not put that in the doc.

**Comment by wardoost** [comment]
@streamich Makes sense to add it if people add a normal function 👍Maybe we could rephrase is to the following to make it more clear?

> A hook internally must use the [React Hooks API](https://reactjs.org/docs/hooks-reference.html)
