### ISSUE TITLE
React state update on an unmounted component with `useSize` and `toBeVisible`

### ISSUE THREAD

**Issue by cdfa** [streamich/react-use#526]
Not completely sure if this is caused by `toBeVisible` or `useSize`, but running both tests from above together results in the second one getting the following error in the console:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
        in Test
```
However, if run separately both tests succeed.

### Code:

```js
import React from "react";
import { render } from "@testing-library/react";
import { useSize } from "react-use";

const childId = "child";

const Test = () => {
  const [sized, { width, height }] = useSize(() => <div />);
  return (
    <>
      {sized}
      <div data-testid={childId} />
    </>
  );
};

describe("<TurnReveal>", () => {
  it("renders children", () => {
    const { container, getByTestId } = render(<Test />);
    const child = getByTestId(childId);
    expect(container).toContainElement(child);
  });

  it("has visible children when it's pose is closed", () => {
    const { getByTestId } = render(<Test />);
    const child = getByTestId(childId);
    expect(child).toBeVisible();
  });
});
```

- `@testing-library/jest-dom` version: `4.0.0`
- `node` version: `v10.15.3`
- ~`npm` (or `yarn`)~ [pnpm](https://pnpm.js.org) version: `3.6.5`
- `react-use` version: `10.5.0`

**Comment by cdfa** [comment]
I discovered waiting a little bit after the render (and wrapping it in an `act`) could resolve the problem, but it's kinda ugly.

```js
const sleep = ms => new Promise(resolve => setTimeout(() => resolve(), ms));

const renderAsync = async (...args) => {
  let result;
  await act(async () => {
    result = render(...args);
    await sleep(100); // Wait for update from useSize hook
  });
  return result;
};
```

**Comment by Belco90** [comment]
Hi!

This is normal when testing async stuff. reac-testing-library has some utils for this:

1. [wait function](https://testing-library.com/docs/dom-testing-library/api-async#wait): it allows to await in the test until something specific happens (e.g. element appears) or just wait little bit. It belongs to dom-testing-library but everything from that library is exported from react-testing-library. I think you can't wait for specific thing to happen, but maybe just doing `await wait()` after the render can help.
2. [findBy query](https://testing-library.com/docs/dom-testing-library/api-queries#findby): this is a simple combination of `getBy` queries and `waitForElement` async util. I'm not sure if you can use it on your test, as the element is there already so you can't actually wait for element to appear.
3. [Recipe for appearance](https://testing-library.com/docs/guide-disappearance#waiting-for-appearance): react-testing-library has nice bunch of recipes for common cases and examples. Maybe you can try to wait until the child is visible with this

I hope this helps, let me know if this solves your problem!

**Comment by cdfa** [comment]
Hello!

1. Tried it, but it seems just `await wait()` doesn't introduce enough of a delay.
2. Tried to use it, but indeed the element is already there, so it's no use.
3. Same as for 2

The problem seems to be that everything gets rendered, but it gets re-rendered when the size updates and that causes the state update on the unmounted component.

**Comment by cdfa** [comment]
I'm starting to wonder if anything can really be done about this, so I'm going to mock it out for now. Feel free to close the issue.
