### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by streamich** [streamich/react-use#546]
**What is the current behavior?**

This test is failing sometimes:

![image](https://user-images.githubusercontent.com/9773803/63382437-04d62100-c39b-11e9-845b-370508b4860b.png)

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

It randomly sometimes fails.

**What is the expected behavior?**

Should always succeed.

**Comment by xobotyi** [comment]
I'll add `raf-stub` to test it predictably;
