### ISSUE TITLE
`useLockBodyScroll` doesn't work in iframe

### ISSUE THREAD

**Issue by Kosai106** [streamich/react-use#550]
**What is the current behavior?**

As the title suggests, the `useLockBodyScroll` hook doesn't appear to have any effect inside of iframes.

[CodeSandbox](https://codesandbox.io/s/react-uselibuselockbodyscroll-3x3z7)

**A little about versions:**  
- _OS_: macOS Mojave 10.14.6
- _Browser_: Google Chrome version 76.0.3809.100 (Official Build) (64-bit)
- _React_: ^16.8.2
- _`react-use`_: ^8.1.2 and 11.0.0 was tested.

**Comment by xobotyi** [comment]
I'll investigate
