### ISSUE TITLE
useSetState infinite loops when following React Hooks Best Practices Guide

### ISSUE THREAD

**Issue by TylerR909** [streamich/react-use#555]
According to the Best Practices described by [React-Hooks FAQ](https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies) and its associated ESLint [react-hooks/exhaustive-deps](https://www.npmjs.com/package/eslint-plugin-react-hooks) plugin, when `setState` is used inside an effect, it should be included in the list of dependencies.
 
**What is the current behavior?**

This causes an infinite loop where `setState` is called from within an effect and a different `setState` is returned from the next `useSetState` hook.

**Steps to reproduce **

https://codesandbox.io/embed/practical-flower-4jpwp

**What is the expected behavior?**

Some sort of smart caching, useMemo, or useCallback around the `setState` generator that depends on the `useState`'s `setState`. Basically a person diligently following the React-Hooks Best Practices should be able to use setState comfortably inside a useEffect without causing infinite rerenders.

**A little about versions:**  
- _OS_: OSX
- _Browser (vendor and version)_: Chrome 76.0.3809.100
- _React_: 16.8.6
- _`react-use`_: 9.0.0 and 11.0.0
- _Did this worked in the previous package version?_ No

**Comment by xobotyi** [comment]
fixed with v11.0.2
