### ISSUE TITLE
Request test for all created or updated hooks

### ISSUE THREAD

**Issue by Belco90** [streamich/react-use#566]
Hi all!

Since we have been putting some effort in adding tests for old hooks and we have proper utils and structure for testing I think we should force every PR adding or modifying hooks to add or update proper tests. Ideally we would configure automated tests for each PR and block them if not passing or decreasing the current coverage, but at least not approving the PR if tests are not updated would be an improvement.

I'm happy to help people struggling with test if that's the case. Maybe a PR template can help. Thoughts?

**Comment by xobotyi** [comment]
Sadly not all hooks are testable via jest.

I'm currently working on contributing.md and PR template. Tomorrow will publish a draft.

**Comment by Belco90** [comment]
Any example of non-testeable hook with jest? We can require a reason at least when no adding tests.

**Comment by xobotyi** [comment]
Those which mocking the behavior on import-time for SSR, like [this](https://github.com/streamich/react-use/blob/master/src/useLockBodyScroll.ts) or [that](https://github.com/streamich/react-use/blob/master/src/useBattery.ts)

**Comment by xobotyi** [comment]
Otherwise i'm absolutely into covering everything as much as possible.

**Comment by streamich** [comment]
So far I've been asking contributors to at least add a Storybook story or tests. But I guess as this library matures we can raise the bar higher.

**Comment by Belco90** [comment]
I just found [Danger JS](https://danger.systems/js/), could be nice option to leave an automatic comment about tests, and also about add/update doc.

**Comment by wardoost** [comment]
@Belco90 Danger JS looks like an interesting 🙂 Could you open a PR with rules only related to tests? It's probably be best to keep the initial config to a minimum as per [documentation](https://danger.systems/js/usage/culture.html). We can add other rules at a later stage.

**Comment by Belco90** [comment]
I'll try to have something this week and create proper PR.
