### ISSUE TITLE
Add useStateWithCallback

### ISSUE THREAD

**Issue by gajus** [streamich/react-use#576]
**Is your feature request related to a problem? Please describe.**

It is often desired to have a callback after `useState` state mutates.

**Describe the solution you'd like**

Add a callback to `useState`.

**Describe alternatives you've considered**

```js
const useStateWithCallback = (defaultState, callback) => {
  const [currentState, setState] = useState(defaultState);

  useUpdateEffect(() => {
    callback(currentState);
  }, [
    currentState,
  ]);

  return [currentState, setState];
};

```

Example:

```js
const [dateRange, setDateRange] = useStateWithCallback({
  from: undefined,
  to: undefined,
  ...props.dateRange,
}, (newDateRange) => {
  props.onChange(newDateRange);
});

```

**Comment by streamich** [comment]
Maybe it could be called `useStateEffect` or `useStateWithEffect`, as that `callback` is basically React effect.

**Comment by gajus** [comment]
> Maybe it could be called useStateEffect or useStateWithEffect, as that callback is basically React effect.

I wouldn't rush with that name or that implementation. It depends where you put the callback, e.g. This might work just as well:

```js
const useStateWithCallback = (defaultState, callback) => {
  const [currentState, setState] = useState(defaultState);
  
  return [
    currentState,
    (newState) => {
      callback(newState);

      setState(newState);
    },
  ];
};

```

**Comment by xobotyi** [comment]
why not to simply use
```js
const [state, setStaet] = React.useState({});
React.useEffect(()=>{
// anything you want
}, [state]);
```
it is way more controllable;

**Comment by gajus** [comment]
> why not to simply use

That entirely depends on what you want the hook to do, as illustrated in my previous comment. I do not recommend any specific implementation. As a consumer, I simply (often) have a use case for a callback straight after `useState` setter is used – as such, having it as a callback makes sense.

In fact, `useLayoutEffect` might make more sense if the intention is to batch changes, i.e.

```js
const useStateWithCallback = (defaultState, callback) => {
  const [currentState, setState] = useState(defaultState);

  useLayoutEffect(() => {
    callback(currentState);
  }, [
    currentState,
  ]);

  return [currentState, setState];
};

```

Correct me if I am wrong, but the latter was the API of `setState` in React class implementation.

**Comment by streamich** [comment]
Yeah, it has it:

![image](https://user-images.githubusercontent.com/9773803/63893549-c4098800-c9ea-11e9-9478-b8af7826d3c6.png)

**Comment by gajus** [comment]
(Ignore my suggestion regarding `useLayoutEffect`. It is not fit for this use case.)

Based on the docs, it seems that it `setState` original API was equivalent to using `useEffect`.

I stick with my original argument that it makes sense to have a callback as a member of `setState` simply because it makes it easier to understand the effect of state change without scanning all instances of `useEffect`.

On the other hand, I do agree with @xobotyi it takes only few lines to implement `useEffect` and it has the benefit of being able to observe multiple states.

No strong feelings either way. Your call @streamich

**Comment by wardoost** [comment]
It feels like this would just be creating hooks because you can. It would probably make a codebase harder to read and understand without knowing all the custom hooks of this library. Shorter code is not better code.

The example from @xobotyi does the same thing and is a lot more clear about what it does (if you know the React Hooks API). Maybe we should add a section to the docs for common patterns like this to the docs?

**Comment by gajus** [comment]
Yes, I agree. Not a good suggestion. Withdrawing.
