### ISSUE TITLE
[Question] How to use useEvent for any target?

### ISSUE THREAD

**Issue by dakiesse** [streamich/react-use#609]
How can I use useEvent for any target when the target wasn't initialed yet? For example:

```jsx
const inputRef = useRef(null)

useEvent('someevent', () => {...}, inputRef.current) // inputRef.current is null now

return (
    <input ref={inputRef} />
)
```

**Comment by edkimmel** [comment]
You should use useState instead of useRef.  That will cause your component to re-render when inputRef is set and will re-execute useEvent with a non-null value.

**Comment by sangdth** [comment]
Hi @dakiesse, have you tried to use the options?
 
```js
const inputRef = useRef(null)
useEvent('someevent', () => {
    ...
}, inputRef.current, { capture: true });

return (
     <input ref={inputRef} />
)
 ```
