### ISSUE TITLE
useSearchParam doesn't work as intended when using HashRouter

### ISSUE THREAD

**Issue by gaspardip** [streamich/react-use#637]
When using `react-router-dom`'s HashRouter, `useSearchParam` doesn't correctly get search params. 

CodeSandbox: https://codesandbox.io/s/great-wave-1r1ts

Now, I don't know if this is a Chromium bug, since it is `location.search` the one that has incorrect values (everything is taken as part of `location.hash`). The result is that `useSearchParam('search')` (or any other param for that matter) returns `null`. I think this can be worked around tho, parsing `location.hash` in search of a query string.

Let me know if you want me to file a PR.

**Comment by gaspardip** [comment]
It seems that actually it's `window.location` the one with wrong values, `react-router-dom` parses the search query just fine (see CodeSandBox `console`, `props.location.search` is correct)

**Comment by wardoost** [comment]
I think it's because query parameters become part of the hash if placed after the hash. Could maybe be fixed by adding a second parameter to define where the search string comes from. This would make this hook more complex then it needs to be as you would need to switch between an implementation with event listeners for `window.location.search` and an implementation with `useEffect`:

```ts
const getValue = (param: string, search: string = location.search) => new URLSearchParams(search).get(param);

export type UseQueryParam = (param: string) => string | null;

const useSearchParam: UseQueryParam = (param, searchLocation) => {
  const [value, setValue] = useState<string | null>(() => getValue(param, searchLocation));

  useEffect(
    () => {
      const onChange = () => {
        setValue(getValue(param, searchLocation));
      };

      if (searchLocation) {
        onChange();
      } else {
        window.addEventListener('popstate', onChange);
        window.addEventListener('pushstate', onChange);
        window.addEventListener('replacestate', onChange);
      }

      return () => {
        if (!searchLocation) {
          window.removeEventListener('popstate', onChange);
          window.removeEventListener('pushstate', onChange);
          window.removeEventListener('replacestate', onChange);
        }
      };
    },
    searchLocation ? [searchLocation] : []
  );

  return value;
};
```

I'm not sure if we want to make `useSearchParams` more complex. When using `HashRouter` you could create a memoized value and have the same effect:

```js
function MyComponent({location}) {
  const search = useMemo(() => {
      return new URLSearchParams(location.search).get('queryParamName')
    },
    [location.search]
  )

  return ...
}
```

**Comment by gaspardip** [comment]
I agree that making the hook that complex isn't a good solution, but this should be addressed somehow. Perhaps update docs so they mention this won't work if you are using hash routing?
