### ISSUE TITLE
[Answered] Question: How can I disable the useClickAway DOM event handler when I don't need it on?

### ISSUE THREAD

**Issue by charlex** [streamich/react-use#656]
Answer: Use a component like this one I wrote:

```jsx
import { useClickAway } from 'react-use';

export const OnClickAway = ({ targetRef, onClickAway }) => {
  useClickAway(targetRef, () => {
    onClickAway();
  });
  return null;
};

```

```jsx
    <OnClickAway
      targetRef={ref}
      onClickAway={() => {
        onToggle(false);
      }}
    />
```

And simply unmount it when you don't need it:

```jsx
// set: listenForEvents = false;
// or: listenForEvents = true;
  <>
    {listenForEvents && <OnClickAway
      targetRef={ref}
      onClickAway={() => {
        onToggle(false);
      }}
    />}
  </>
```

PS: I think the hook could also implement this as an option, like this:

```jsx
useClickAway(..., { disabled }); // or `enabled` or `stopListening` or `listening` ...
```

EDIT: I'll close this ticket shortly so as not to clutter up the issues, but just to give those watching just open tickets a chance to respond if they want to. There might be a better solution, or different answer than this.

**Comment by jmlavoier** [comment]
Hey man. If you still need a solution like this, try out the [react-use-clickout](https://github.com/jmlavoier/react-use-clickout). It was created to just solve a problem like this.
