### ISSUE TITLE
Adding sessionStorage - API options

### ISSUE THREAD

**Issue by ajoslin** [streamich/react-use#66]
Would like to add useSessionStorage.

Options API-wise:

1. Just copy-paste useLocalStorage and `s/local/session`
2. In useLocalStorage.ts, add a parameter called `storageKey` that defaults to `'localStorage'` and have useSessionStorage just call that. Then in useLocalStorage, `s/localStorage/window[storageKey]`

What would you prefer?

**Comment by streamich** [comment]
Probably better to copy-paste. Although, I don't have strong opinion on that if options 2 works out smoothly.

There is `storage` event one can listen on `window`, that could be added to `useLocalStorage`, don't know how it works with session storage.

**Comment by ajoslin** [comment]
I like copy-paste here, too. Opening a  PR, thanks.
