### ISSUE TITLE
useAsyncFn add race-condition solution

### ISSUE THREAD

**Issue by lwyj123** [streamich/react-use#669]
**Is your feature request related to a problem? Please describe.**
There is a [race-condition](https://overreacted.io/a-complete-guide-to-useeffect/#speaking-of-race-conditions) problem in some of my use-cases. For example the pagination. if you change the page very quickly and using `useEffect` for fetch data, sometimes the browser will receive the previous request's response in the end. so the data on the page is wrong.

**Describe the solution you'd like**
I would like the `react-use` add a hook for race-condition or enhance `useAsyncFn` for solving this kind of problems by default

**Describe alternatives you've considered**
It's good for user experience. And this feature will save my day :)

**Comment by streamich** [comment]
Can you please provide an example of a race condition you would like this library to solve?

**Comment by echoulen** [comment]
I notify this line:

https://github.com/streamich/react-use/blob/master/src/useAsyncFn.ts#L42

This condition makes sure that the state updated by the last call only, is it the solution for race-condition?

**Comment by lwyj123** [comment]
@echoulen Yes, the commit [022fa0b7b77d](https://github.com/streamich/react-use/commit/022fa0b7b77d582a10c6ca61a3dcd901770011c8) resolve this problem. close
