### ISSUE TITLE
Seems to be incompatible with IE

### ISSUE THREAD

**Issue by andyyxw** [streamich/react-use#691]
**What is the current behavior?**
incompatible with IE(11)

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

**What is the expected behavior?**
As compatible as possible with IE9 or above。

**A little about versions:**  
- _OS_:  Windows10
- _Browser (vendor and version)_: IE11
- _React_:  16.8.6
- _`react-use`_:  12.5.0
- _Did this worked in the previous package version?_ NO

**Comment by streamich** [comment]
What issues do you experience in IE?

**Comment by xobotyi** [comment]
@streamich the problem been related to harmonic interval lib, which is fixed now.
