### ISSUE TITLE
Remove the react-wait from package?

### ISSUE THREAD

**Issue by xobotyi** [streamich/react-use#708]
Do we really need that reexport in library?
It's only reexporting the default hook provided by `react-wait` itself. As for me there is absolutely no sense to have that dependency.

**Comment by qianL93** [comment]
Agreed, It is unnecessary to export again. And we will have React.Suspense for most  scenarios.

**Comment by xobotyi** [comment]
@streamich maybe merge #711 and do a major release?

**Comment by streamich** [comment]
@xobotyi I've sent you a Slack invite.
