### ISSUE TITLE
X and Y missing from useMeasure

### ISSUE THREAD

**Issue by brewern** [streamich/react-use#716]
Property 'x' does not exist on type 'ContentRect'.

When using `const [ref, { x, y, width, height }] = useMeasure();`, the console reports the property X and Y do not exist. Reviewing the source for useMeasure and they are missing from the internal state. I do not see X and Y when reviewing the spec for resize observer.

Was this going to be implemented another way? Or does it just need to be removed from the documentation?

**Comment by streamich** [comment]
Thanks, [I've removed](https://github.com/streamich/react-use/commit/8538385afb6e41ffa0037e8777bcd1dff5f7703a) them from docs, please use `top` and `left` instead.

**Comment by streamich** [comment]
Actually reverted it back.

`x` and `y` were not set on initial render, please see if it is now fixed.
