### ISSUE TITLE
useTitle broken in Next.js SSR (document is not defined)

### ISSUE THREAD

**Issue by ecwyne** [streamich/react-use#749]
**What is the current behavior?**
Throws error on server `ReferenceError: document is not defined`
**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**
Use `useTitle` hook in Next.js project
**What is the expected behavior?**
Only sets title on client?
**A little about versions:**  
- _OS_:  `macOS Catalina`
- _Browser (vendor and version)_: `Chrome 78.0.3904.70`
- _React_: `16.11.0`
- _`react-use`_:  `13.2.1`
- _Did this worked in the previous package version?_
Yes

Apears to be a consequence of https://github.com/streamich/react-use/commit/a13326779ffd6885ac531240b984a77bcad3bee6

**Comment by xobotyi** [comment]
Hm, due to now `useTitile` is synchronous hook it evaluets on server side, looks like next.js or even react itself been blocking the `useEffect` hooks on the sevrer side 🤔

**Comment by xobotyi** [comment]
Ill fix it today

**Comment by ecwyne** [comment]
Could be as simple as

**Comment by ecwyne** [comment]
Could be as simple as

```js
if (typeof document !== 'undefined && t.current !== title) {
    document.title = t.current = title;
}
```

**Comment by xobotyi** [comment]
@ecwyne i know, just dont have a time yet. In 3-4 hours i think ill push the fix.

**Comment by xobotyi** [comment]
@ecwyne chek new version pls.

**Comment by ecwyne** [comment]
@xobotyi still getting `ReferenceError: document is not defined`

**Comment by ecwyne** [comment]
I think it needs to be `typeof document === 'undefined'`

**Comment by xobotyi** [comment]
That bad >_> okay, fix will be done in 10-15 minutes i suppose.

**Comment by xobotyi** [comment]
@ecwyne and noooow =) it should be fine.
