### ISSUE TITLE
Does react-use support tree shaking?

### ISSUE THREAD

**Issue by rjkz808** [streamich/react-use#777]
**Is your feature request related to a problem? Please describe.**

[Bundlephobia shows me](https://bundlephobia.com/result?p=react-use@13.8.0) that the minified version of `react-use` weights 56.3 kB and increases the download time for 314 ms. It's not so far from `lodash`. Some applications do not require the usage of all the hooks provided by `react-use`. So, other parts of the library become an excess load for some projects.

**Describe the solution you'd like**

I think it would be nice to have support of webpack tree shaking (or similar technologies). The benefit of this is that the application can be still fast and lightweight while using only a small part of `react-use`.

**Comment by xobotyi** [comment]
First of all it is recommended to import hooks directly:
`import useUpdate from 'react-use/esm/useUpdate';` but not `import {useUpdate} from 'react-use';`.
Both works but first will not include all unused hooks to the bundle.

About tree-shaking, as I remember - there is nothing package can do, it is bundler's feature.

**Comment by rjkz808** [comment]
Ok, thank you! I'm closing this one.

**Comment by streamich** [comment]
[We have `sideEffects: false` set](https://github.com/streamich/react-use/blob/master/package.json#L7), which should allow tree-shaking in Webpack.

Also [`Usage.md`](https://github.com/streamich/react-use/blob/master/docs/Usage.md) mentions a couple of ways to import hooks.
