### ISSUE TITLE
useSetState state coverage

### ISSUE THREAD

**Issue by xianjie-li** [streamich/react-use#789]
**Is your feature request related to a problem? Please describe.**
```jsx
// a query state
const [query, setQuery] = useSetState({
  page: 1,
});

// add some state
<Input onChange={({ value }) => setQuery({ keyword: value }) } />
<Date onChange={({ data }) => setQuery({ date}) } />
<Gate onChange={({ gate}) => setQuery({ gate }) } />

// and if all I want is ?page=1, i need
setQuery({ 
  page: 1,
  keyword: '',
  date: '',
  gate: ''
});
```

**Describe the solution you'd like**
It's different from setState. I don't know if it's reasonable.
```jsx
const [query, setQuery, setOverState] = useSetState({
  page: 1,
});

/*  ... */

setOverState({ page: 1 });
```

**Describe alternatives you've considered**

**Comment by streamich** [comment]
Is it possible to do what you are suggesting using React's class components using `this.setState()`?

**Comment by xobotyi** [comment]
@streamich no, but i think we can implement that method. IMO it would be handy in some use cases.

**Comment by nikasepiskveradze** [comment]
I think that feature is already in implementation, because if you pass new or existing value to "setter" function it will merge or override to corresponding property.
This issue is outdated I guess.
