### ISSUE TITLE
why do you use return in the useUpdateEffect ?

### ISSUE THREAD

**Issue by mynameissuwei** [streamich/react-use#793]
**What is the current behavior?**
   why do you use return in the useUpdateEffect ? 

**What is the expected behavior?**

**A little about versions:**  
- _React_: 16.8.0
- _`react-use`_: 13.8.0

  today i am reading your code ， when i read the useUpdateEffect this function ， i am confused ， why do you use the return in the useUpdateEffect ， return is used in the Effects with Cleanup.
but useUpdateEffect is updating lifeCycle function .  i  think using return is not semantization.
Should useUpdateEffect be typed something like...

```
const useUpdateEffect: typeof useEffect = (effect, deps) => {
  const isInitialMount = useRef(true);

  useEffect(() => {
    if (isInitialMount.current) {
      isInitialMount.current = false;
    } else {
      effect();
    }
  }, deps);
}

```
thanks ， this is my first issue ， i like your repository.  i am learning your code to practice my hook skill .

**Comment by xobotyi** [comment]
Because someone might need the cleanup on updates.

This hook mimics the native `useEffect` behaviour except the first render.

**Comment by mynameissuwei** [comment]
Thanks, i understand.

**Comment by YXK666** [comment]
> Thanks, i understand.

good job man
