### ISSUE TITLE
useMediaDevices(): TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by tayay** [streamich/react-use#820]
I use `useMediaDevices()`.
An error occurs when `navigator.mediaDevices` is undefined.
Is it possible to prevent an error even if `navigator.mediaDevices` is undefined?
thanks.

![WS000000](https://user-images.githubusercontent.com/36296084/70218318-20b4d580-1786-11ea-84d6-f01f0444f5e1.JPG)

**Comment by OBe95** [comment]
Hi @streamich, I just created a [PR](https://github.com/streamich/react-use/pull/830) for this issue
