### ISSUE TITLE
useLocalStorage should support JSON.stringify replacer's and reviver's.

### ISSUE THREAD

**Issue by cosullivan** [streamich/react-use#834]
I am using Typescript and have a Type that contains Set<T>'s. When using useLocalStorage this fails because Set<T>'s can't be serialized with JSON.stringify and as such they disappear from my type.

The solution to having JSON.stringify work on Set's is to use the replacer function on JSON.stringify and the reviver function on JSON.parse. 

It would be good if useLocalStorage could take in these functions as optional parameters to be used during stringify and parse or alternatively callbacks that control the serialization and deserialization process.

**Comment by streamich** [comment]
Currently, `JSON.stringify` is an internal implementation, exposing replacer and reviver would expose that internal detail. What are the benefits/drawbacks of normalizing or serializing the data before passing it to the `useLocalStorage` hook?

**Comment by cosullivan** [comment]
That's fair enough about not wanting to expose the internal implementation, the issue is that the internal implementation can silently fail.

I do currently have a custom hook which wraps the useLocalStorage hook and performs the serialization before and after and that works fine, but it's not as succinct as just being able to pass in a serializer & deserializer function. 

Given that the constraint/api on localStorage is to use string values perhaps having optional parameters one for the serializer which is _T => string_ and once for the deserializer which is _string => T_ and the default impementation of those is JSON.stringify and JSON.parse?

**Comment by streamich** [comment]
Yeah, I like the idea of serializer to be an optional argument.

**Comment by ayush987goyal** [comment]
@streamich @cosullivan Hey guys! Can you please review the above PR?

**Comment by cosullivan** [comment]
This API change will work nicely for me.

Thanks, Cain.

**Comment by ayush987goyal** [comment]
@streamich This can be closed. Merged with #896
