### ISSUE TITLE
useNetwork unexpected value in most common browsers.

### ISSUE THREAD

**Issue by bebbi** [streamich/react-use#855]
**What is the current behavior?**

I've migrated over here from `react-detect-offline` and noticed the support for online checking is very poor in this hook.

The code line

```
connection = navigator.connection || navigator.mozConnection || navigator.webkitConnection
```

returns `undefined` on at least desktop firefox, desktop safari, iOS.
See https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API for current browser support.

In this hook's code this results in a falsy value for the `online` prop in most browsers.

Maybe `react-detect-offline` could be consulted for an approach that has been pretty robust in my experience.

**Comment by streamich** [comment]
`react-detect-offline` executes HTTP requests manually to test if there is a connection if `navigator` does not support on-line API. Maybe there is a polyfill for `navigator.connection` that also executes HTTP requests?

**Comment by bebbi** [comment]
Cool idea.

A small first improvement could be to just rely on `navigator.onLine` and its events as done [here](https://github.com/oieduardorabelo/use-navigator-online) and supply the other props if available.

Since I only need the online status I'm using the linked hook and it works very reliably so far.
