### ISSUE TITLE
keyboardJs.bind is not a function

### ISSUE THREAD

**Issue by lukethacoder** [streamich/react-use#877]
**What is the current behavior?**

useKeybordJs hook is not working due to `keyboardJs.bind is not a function` error within storybook and non-storybook usage.

**Steps to reproduce**

react-use Storybook Docs Demo: https://streamich.github.io/react-use/?path=/story/sensors-usekeyboardjs--demo

or personal usage scenario

```javascript
import React from 'react'
import useKeyboardJs from 'react-use/lib/useKeyboardJs'

export const Devtools = () => {
  const [isPressed] = useKeyboardJs('a + b')

  return <p>{isPressed}</p>
}z
``` 

**A little about versions:**  
- _OS_: Windows
- _Browser (vendor and version)_: Firefox Dev, Chrome, Chrome Dev
- _NPM packages_: 
```json
"keyboardjs": "^2.5.1",
"next": "9.1.7",
"react-use": "^13.14.3"
```

**Possible solutions?**

- might be an issue with keyboardjs and not react-use?
- `useKey`, `useKeyPress` and/or `useKeyPressEvent` could be expanded to replace keyboardjs
- recreate the functionality of keyboardjs from scratch?

**Comment by tangzijun** [comment]
The same problem, I copied the source code and used it, but there was no problem, but the import did not work, I do not know what the reason is

**Comment by eddiewang** [comment]
any updates on this? still broken on my end.

**Comment by manishsundriyal** [comment]
@streamich I have looked into the issue and created a PR https://github.com/streamich/react-use/pull/1129. Let me know if it requires any other update or if you any concerns.

**Comment by danawoodman** [comment]
Same issue using the keyboardjs `2.5.1` and react-use `14.1.1`.

**Comment by manishsundriyal** [comment]
@lukethacoder @streamich  I think, this has been mentioned and fixed in https://github.com/streamich/react-use/pull/1129.
Also the demo is working fine for now: https://streamich.github.io/react-use/?path=/story/sensors-usekeyboardjs--demo

Can you please recheck? and either close this or add in some more details.

**Comment by lukethacoder** [comment]
Working very nicely on the demo, but have run into different issues.

Will close this one off and open up another ticket if I can't get it working. It doesnt look to be related to the `useKeyboardJs` hook.

`Can't resolve 'react-universal-interface'`
