### ISSUE TITLE
useToggle called twice in a row has unexpected behavior

### ISSUE THREAD

**Issue by malerba118** [streamich/react-use#89]
useToggle called twice in a row should be a no-op, but acts as if toggle was only called once.
https://codesandbox.io/s/p0r6m3zk7

Line 17 in useToggle should become setValue(prevValue => !prevValue)
https://github.com/streamich/react-use/blob/master/src/useToggle.ts#L17

Whenever the next state value depends on a previous state value, the state setter should take a function and return the new state.

**Comment by TrySound** [comment]
This component is implemented in wrong way. Batching and async doesn't work with it. State based updates should be done with function updater like `setToggle(v => !v)`.

**Comment by malerba118** [comment]
I'm using it as per the docs. 

<img width="539" alt="screen shot 2019-01-04 at 1 28 19 pm" src="https://user-images.githubusercontent.com/5760059/50706950-f6621180-1024-11e9-89a0-bac8f0eb46e0.png">

The toggle function accepts one argument, an optional boolean, not a function.

<img width="420" alt="screen shot 2019-01-04 at 1 27 57 pm" src="https://user-images.githubusercontent.com/5760059/50707295-f6aedc80-1025-11e9-8d7b-4a825d6a0f0f.png">

The whole point is to delegate toggling logic to the useToggle hook. If the toggling logic was required in the updater function, this useToggle hook would have no purpose. It would just be a no-op wrapper around useState.

**Comment by TrySound** [comment]
I said implementation is wrong. Not usage.

**Comment by malerba118** [comment]
Apologies, I thought you were referring to my implementation of it.

**Comment by streamich** [comment]
Thanks guys, added your suggestion:

- https://github.com/streamich/react-use/releases/tag/v5.2.1

**Comment by benneq** [comment]
It's been released today. Is it working now?

**Comment by streamich** [comment]
I believe this has been fixed.
