### ISSUE TITLE
Question: useRafState use case

### ISSUE THREAD

**Issue by donifer** [streamich/react-use#897]
Can someone please explain me the use case for `useRafState`? I'm trying to read about `raf` but I don't get it yet.

Should this be used when updating the state is high priority? Or the exact opposite?

**Comment by streamich** [comment]
It will update the state in the next animation frame, which usually is after 16ms, so it is low priority.

It is useful in a scenario where you would need to debounce the data or would use `requestAnimationFrame` to "debounce". For example, if you subscribe to a scroll event it could potentially fire a dozen times in 16ms, there is no need to update the state every time that scroll event would fire, so instead you can use this hook which will make sure state is updated only the next animation frame.

**Comment by FlickerLogicalStack** [comment]
Video about why **16ms** exactly matters [_Lin Clark_ at React Conf 2017 about `React Fiber`](https://youtu.be/ZCuYPiUIONs)

**Comment by donifer** [comment]
Thanks so much for the explanation and video. Everything makes more sense now. ❤️
