### ISSUE TITLE
Improving error handling in useCopyToClipboard

### ISSUE THREAD

**Issue by cleverjam** [streamich/react-use#898]
**What is the current behavior?**

If the value passed to copy-to-clipboard is anything but a string, a `window.prompt` is invoked and even if a value is entered it does not get copied to the clipboard.

![image](https://user-images.githubusercontent.com/12721875/72485979-15b28380-37cf-11ea-90b5-573ed025b980.png)

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

 👉🏼 [code sandbox](https://codesandbox.io/s/clever-blackwell-gpxrd?fontsize=14&hidenavigation=1&theme=dark)
 1. Click on copy text button
 2. Enter any string in the prompt 
 3. Click 'Ok'
 4. Observe the state values 
 5. Paste your clipboard somewhere to see if anything was copied.

**What is the expected behavior?**

The prompt was an unexpected behavior, and not sure if this was intentional (it is invoked by the copy-to-clipboard package). But if one will be shown the text should at least be copied to the clipboard.

I propose making a change and only invoking `copy-to-clipboard` with valid strings, and ensuring the `{value, noUserInteraction, error}` values are updated accordingly with each call. If this acceptable I am willing to open a PR with the changes.

**A little about versions:**  
- _OS_: macOS Catalina 10.15.2 
- _Browser (vendor and version)_: Safari
- _React_: 
- _`react-use`_: 
- _Did this worked in the previous package version?_

**Comment by cleverjam** [comment]
To provide more context, I was attempting to help increase the code coverage as requested in the contribution guide. 

Writing unit tests for this hook, I realize that passing an invalid value to `copyToClipboard` does not result in an error state, which was odd. 

I could work on improving the hook + the tests if my proposed change is accepted.

Draft PR for ref: #899

**Comment by streamich** [comment]
Proposed change here sounds good to me.

**Comment by cleverjam** [comment]
Cool, I'll work on this

**Comment by cleverjam** [comment]
Closing this issue since the PR is already merged.
