### ISSUE TITLE
useMountedState doesn't seem to work properly when server rendering.

### ISSUE THREAD

**Issue by andrico1234** [streamich/react-use#926]
**What is the current behavior?**

```
function ServerRenderedComponent() {
  const isMounted = useMountedState();

  if (!isMounted) {
    return null
  }

  return (
    <p>{window.location}</p> // or any window/document object
  )
}

```

This causes my Gatsby build to fail, because the document/window objects aren't available on the server side. I fix this by doing:

```


function TourSkillTree() {
  const [componentHasMounted, setComponentIsMountedState] = useState(false);

  useEffectOnce(() => {
    setComponentIsMountedState(true);
  });

  if (!componentHasMounted) {
    return <Loader />;
  }

  return (
    <p>{window.location}</p> // or any window/document object
  )
}
```

But it's more verbose, and less declarative (which is one of the reasons I use `react-use` in the first place. If this is a known issue and requires fixing, I can look into an MR for this.

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

**What is the expected behavior?**

**A little about versions:**  
- _OS_: 
- _Browser (vendor and version)_: 
- _React_: 16.12
- _`react-use`_: 12.2.0 
- _Did this worked in the previous package version?_

**Comment by xobotyi** [comment]
If to be a dick, I'd send you back to the docs, buuut)
`useMountedState` returns a function!

**Comment by andrico1234** [comment]
ha! you're completely right. Let me try the code again. If it works (which it likely will), i'll close the issue.

Thanks
