### ISSUE TITLE
useAsyncFn: keeping the previous state when start running the async function

### ISSUE THREAD

**Issue by echoulen** [streamich/react-use#934]
**Is your feature request related to a problem? Please describe.**
the initialState.value of useAsyncFn will be clean when start running the async function

**Describe the solution you'd like**
keep the previous state unless `loading` property when start running the async function

**Comment by Granipouss** [comment]
Hello there,

I feel like merging the state of various function executions can be a bit messy. Did you think about holding multiple states ? Maybe returning a state reference at each execution ?

What is your use case ?

Cheers,

**Comment by echoulen** [comment]
Hi @Granipouss,

You are right, maybe I can custom the hook myself without modifying the useAsyncFn,

Actually I did, I will close the issue and PR if you feeling keeping the value will be a bit messy, it's fine for me.

**Comment by Granipouss** [comment]
I would wait for other opinions before closing it all

**Comment by echoulen** [comment]
This PR has been merged, close the issue.
