### ISSUE TITLE
useVideo ref is erroneously typed

### ISSUE THREAD

**Issue by omasback** [streamich/react-use#969]
**What is the current behavior?**

The type hinted for the useVideo ref is 

`const ref: {
    current: HTMLAudioElement | null;
}`

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

file: `react-use/lib/useVideo.d.ts`

content: 

`/// <reference types="react" />
declare const useVideo: (elOrProps: import("./util/createHTMLMediaHook").HTMLMediaProps | import("react").ReactElement<import("./util/createHTMLMediaHook").HTMLMediaProps, string | ((props: any) => import("react").ReactElement<any, string | any | (new (props: any) => import("react").Component<any, any, any>)> | null) | (new (props: any) => import("react").Component<any, any, any>)>) => [import("react").ReactElement<import("./util/createHTMLMediaHook").HTMLMediaProps, string | ((props: any) => import("react").ReactElement<any, string | any | (new (props: any) => import("react").Component<any, any, any>)> | null) | (new (props: any) => import("react").Component<any, any, any>)>, import("./util/createHTMLMediaHook").HTMLMediaState, import("./util/createHTMLMediaHook").HTMLMediaControls, {
    current: HTMLAudioElement | null;
}];
export default useVideo;
`

`const [video, state, controls, ref] = useVideo(
    <video
      src={
        'https://anything.com/video.mp4'
      }
      controls
    ></video>
`

**What is the expected behavior?**

`const ref: {
    current: HTMLVideoElement | null;
}`

**A little about versions:**  
- _VSCode_: 1.42.0
- _Typescript_: 3.7.5
- _React_: 16.12.0
- _`react-use`_: 13.24.0
- _Did this worked in the previous package version?_

**Comment by streamich** [comment]
I guess its this line:

https://github.com/streamich/react-use/blob/master/src/util/createHTMLMediaHook.ts#L31

**Comment by omasback** [comment]
Also here. 

https://github.com/streamich/react-use/blob/master/src/util/createHTMLMediaHook.ts#L50

It wouldn't have been a problem but I was trying to access `ref.current.videoWidth`, which doesnt exist on HTMLAudioElement

**Comment by streamich** [comment]
Also this error could be made more abstract, to include possibility of `<video>`:

https://github.com/streamich/react-use/blob/master/src/util/createHTMLMediaHook.ts#L200-L202

**Comment by n4bb12** [comment]
Is there a way I can contribute to solve this? Should I create a new PR?
